### ISSUE TITLE
Multiple types of copper

### ISSUE THREAD

**Issue by redaktiv** [AllTheMods/ATM-5#100]
I only find Mekanism Copper Ore in my world but there are some problems in 1.19

Smelting Mekanism copper ore in a silent mechanism furnace gives you mekanism copper ingots
Smelting mekanism copper ore in a mekanism smelting factory gives you silent mechanism copper ingots.
The same goes for mekaniskm copper dust.

A mekanism copper ingot gives you silent mechanism copper nuggets.

And last. 9 copper ingots from mekanism or silent mechanism gives you a silent mechanism copper block BUT if you but copper ingots in a compacting drawer from Storage drawers it gives you the ingot you put in (mekanism or silent mechanism), silent mechanism nuggets and Blue power blocks.

**Comment by whatthedrunk** [comment]
I removed the copper, tin and silver ingot recipes that cause the conversion to happen. Converting from blocks and nuggets now gives you the same output as smelting. If you notice any other conflicts after testing v1.20 coming out later today let me know.
