### ISSUE TITLE
[1.20] Nature's Aura Book no longer working with latest version

### ISSUE THREAD

**Issue by Gagtech** [AllTheMods/ATM-5#103]
After the latest ATM5 update, the Nature's Aura book no longer works.

## Expected Behavior
The book should open.

## Current Behavior
Nothing, generates error in console.

## Possible Solution
Unknown. Update mod? (The mod author appears to have removed the latest version used in this pack from the website, likely due to this issue)

## Steps to Reproduce
Open Nature's Aura book/progress through the book.

## Log
https://gist.github.com/Gagtech/873a01ec0da47808c6e47c8e511e8e77

## Detailed Description
Wait for mod update.

**Comment by whatthedrunk** [comment]
Version 1.20a hotfix will be out shortly thanks for the report!
