### ISSUE TITLE
Mystical Agriculture Obsidian Seeds do not craft

### ISSUE THREAD

**Issue by SPL17SCR33N** [AllTheMods/ATM-5#104]
## Expected Behavior

You put 4 obsidian and 4 tertium on the pedestals, add a seed and it should craft.

## Current Behavior

The craft processes, absorbs my items and the seed does not craft.

## Steps to Reproduce

1. Put items needed to craft obsidian seeds into the MA seed crafting pedestals
2. Items will be absorbed
3. Seed will not be crafted and pedestal will be empty.
4.

**Comment by VPower512** [comment]
in my game there is no problem
it works fine

**Comment by whatthedrunk** [comment]
I was having this issue before but on the new v1.24 that is almost out it works for me again.
