### ISSUE TITLE
Just wanted to share a starting screen bug after updating to Version 1.21

### ISSUE THREAD

**Issue by Markus292** [AllTheMods/ATM-5#105]
## Expected Behavior

![image](https://user-images.githubusercontent.com/58335594/80800727-7d3be580-8baa-11ea-879a-1d8487d6410c.png)
Together with the usual start page for the modpack.

## Current Behavior

![ATM 5 Just found this after starting the 1 21 Version not sure if this is intented ](https://user-images.githubusercontent.com/58335594/80800326-7bbded80-8ba9-11ea-9e3b-1851e5bec5bb.png)

## Possible Solution

Maybe edit something in the starting screen files. But I wouldn´t know where to find them or how to do it because I am a potato when it comes to technic. 

## Steps to Reproduce

1. I just updated ATM 5 to version 1.21 on Twitch
2. I also pasted  my backup, journey map and ressource packs which I used in the 1.20a version into the updated 1.21 version.
3. Started the modpack.
4. And arrived at this starting screen. 

## Detailed Description

The ATM 5 Logo after start up is completly gone. I didn´t look into code because im not good with it.

**Comment by whatthedrunk** [comment]
I created a new profile and it shows up fine. Did you copy over the packmenu folder when you moved stuff around?

**Comment by Markus292** [comment]
I managed to fix it. It had only half of the size of the ´packmenu´ that I had in the 1.20a version. So i copied the packmenu from version 1.20a into the 1.21 version folder and now I have the regular start up. 
Ty for help we can close this thread now.
