### ISSUE TITLE
Reliquary items not dropping from blazes and endermen

### ISSUE THREAD

**Issue by jerry2478** [AllTheMods/ATM-5#106]
nebulous heart and molten cores are not dropping from endermen and blazes.

## Expected Behavior
The mod pack creator says they should be a one in ten drop.

## Current Behavior
after killing about 1300 endermen by hand (way more with a player trap) and 78 blaze neither item has dropped for me. Zombie hearts drop fine as do other drops from the pack.

## Steps to Reproduce

1. Kill endermen
2.???
3. do not profit

**Comment by Minithra** [comment]
Just tested it on our server, it works just fine? Manually killed an enderman, and ran soul shard spawners with player traps, both the molten cores and nebulous hearts dropped.

**Comment by whatthedrunk** [comment]
I just testing as well and its working fine. Thanks for the report and response!
