### ISSUE TITLE
Incompatible Server Warning

### ISSUE THREAD

**Issue by miffet** [AllTheMods/ATM-5#107]
Have 1.21 installed from Twitch, used the Simple Server Files for 1.21 to load a linux server.

When server is fully started (been running all day), the client shows a red X on it with a description "Incompatible FML modded server, Server modlist is not compatible"

Players can join and it seems to be working OK.

![Capture](https://user-images.githubusercontent.com/54242528/80848361-a07d8980-8bd8-11ea-9f25-d92c83275b7b.PNG)

**Comment by whatthedrunk** [comment]
This is a forge issue. The server files do not have inventory profiles and the client does. Also if you have any server profiling mods such as spark you will get this as well.
