### ISSUE TITLE
Potato tag conflict inhibits users from making VeggieWay's Carb Powder

### ISSUE THREAD

**Issue by utoc** [AllTheMods/ATM-5#108]
## Expected Behavior
8 Potates and 1 Drying Agent (PPP,PDP,PPP) should net Carb Powder.

## Current Behavior
8 Potates and 1 Drying Agent (PPP,PDP,PPP) nets Vitamin Powder

This is caused by the Rats mod adding potatoes as forge:vegetables (See discord #atm5-help from Mod Author @kwpugh looking in to this) which causes the recipe for Vitamin Powder to overlap onto Carb Powder since potates are both a carb and vegetable (and delicious).  

## Possible Solution
Remove the recipes in Crafttweaker for Carb Powder then re-add as CCC,CDC,CCC (forge:carbs), drying agent) for Carb Powder. 

Alternatively you could remove the forge:vegetables tag from the humble potate.

Veggie Way author will get with the Rats author to find a long-term solution and this recipe change requested will be a bandaid until the two mods find a happy place.

## Steps to reproduce:

Put 8 potatoes in a crafting table in a circle with a drying agent in the middle.  You get vitamin powder.  You should have gotten carb powder.

See a happy picture below:

![Discord_PcbpPktulQ](https://user-images.githubusercontent.com/11995956/80871476-7b3d5980-8c72-11ea-81df-030760b9087e.png)

**Comment by kwpugh** [comment]
You folks can close this.   The latest release of VeggieWay removes Forge tag-based recipes to avoid conflict.   All of the powders can be made with vanilla and ingredients from my mod only.   I'm am exploring another, less conflict-prone method.

**Comment by whatthedrunk** [comment]
I will push an update tomorrow with the fix. Thanks.
