### ISSUE TITLE
GLFW error 65539: invalid key 4

### ISSUE THREAD

**Issue by DynamiteGamer** [AllTheMods/ATM-5#109]
Hi i have a probleme with this modpack and an other with the same version of minecraft
I can play one time then when i want to play a second time i have this error 

![Capture](https://user-images.githubusercontent.com/64704680/80872717-0723a580-8cb4-11ea-91d3-5e7d1bb7c509.PNG)

I put the log if it can help to solve the probleme

https://pastebin.com/cE0FLG6c

 I try to update all drivers but it has no effect

**Comment by Quu1337** [comment]
binded mousebuttons? dont do that. also please pastebin the logs.

**Comment by DynamiteGamer** [comment]
> binded mousebuttons? dont do that. also please pastebin the logs.

i binded mousebuttons on every version and it work 
sorry for the pastebin i'm new but i did it

**Comment by whatthedrunk** [comment]
Duplicate of #22 and #32
