### ISSUE TITLE
[1.21] Farming for Blockheads Crashed Server

### ISSUE THREAD

**Issue by Gagtech** [AllTheMods/ATM-5#110]
## Expected Behavior
Not sure what happened.

## Current Behavior
Crashed the server.

## Possible Solution
Not sure

## Steps to Reproduce
Haven't been able to reproduce yet. 

## Log
https://pastebin.com/rmuKRcZG

## Detailed Description
NA

**Comment by Gagtech** [comment]
Mod author confirmed issue:

https://github.com/blay09/FarmingForBlockheads/issues/90

**Comment by whatthedrunk** [comment]
This should be updated and fixed in today's update .
