### ISSUE TITLE
Server crashing on initial startup

### ISSUE THREAD

**Issue by OoTMaestro** [AllTheMods/ATM-5#112]
## Expected Behavior

Using the included shell/batch commands the server should start successfully

## Current Behavior

server crashes at certain point (crash logs) in initialization 

## Possible Solution

error logs point to Solar Flux Reborn?

## Steps to Reproduce

1. execute startserver.sh/bat
2.
3.
4.

## Log

Crash Logs: https://gist.github.com/OoTMaestro/a6a94cda80c30dc24f527e03f3c19bac
Complete Latest Log: https://gist.github.com/OoTMaestro/f663e381c989b597c9a47a5c21ec11b2

## Detailed Description

Server refuses to start, I've tried changing java args, verifying java installs, versions for java, switching between linux and windows, not having any luck, sure would appreciate any pointers if I'm doing something wrong

**Comment by OoTMaestro** [comment]
So immediately after posting this I tried doing the same process on my CentOS VM and it started up flawlessly, and running great. So now I'm going to be trying to figure out what's different between these machines and figure out why it failed so terribly on Ubuntu and Windows

**Comment by Quu1337** [comment]
those load errors are "normal" and might happen very often, just restart till everything loads. its java.

**Comment by OoTMaestro** [comment]
I thought so at first too Quu1337 but what was fishy was that a majority of the included java arguments by the pack creators were throwing errors, so I had to modify the start files. Also I tried doing exactly like you said but I was on try #40 or something like that before posting here, however I found the issue. 

I had openjdk-11 installed for some reason, backtracked to openjdk-8 and it was a first time go........

**Comment by Quu1337** [comment]
ah, didnt spot the Java version from logs. minecraft needs Java 8, anything else and it juet fails to run properly.
