### ISSUE TITLE
Fluid/tank duplication using CookingforBlockhead sink

### ISSUE THREAD

**Issue by Slychocobo** [AllTheMods/ATM-5#115]
It's possible to duplicate a empty Mechanism 'Basic Fluid Tank' by right-click using it on a CFB Sink, It places one in front of the sink (empty) and another in your hand containing 1 bucket of fluid.

I was also able to clone a Quark Tank with 1000mb of a duplicated liquid (Filled with Diesel via the same method, but this was far less reproducible, while the Mek tank seems quite consistent. 

## Expected Behavior
tank should fill with fluid, not create a duplicate tank in world

## Current Behavior
Mek tank is duplicated and a second is placed in hand with 400mb of water

## Steps to Reproduce

1. Right-click Mek tank on CFB Sink

**Comment by whatthedrunk** [comment]
This seems to have been fixed by the dev, thanks!
