### ISSUE TITLE
Biofuel Generator crashes

### ISSUE THREAD

**Issue by howradisit** [AllTheMods/ATM-5#116]
## Expected Behavior

The Biofuel Generator should open to an interface

## Current Behavior

The game crashes instead of launching the interface.

## Steps to Reproduce

1. Right-click on Biofuel Generator
2. Crash

## Log

https://gist.github.com/howradisit/c09e4852475196b0da806d4356b9315e

## Detailed Description

Whenever I right-click on the biofuel generator from Industrial Foregoing, the game crashes.

**Comment by whatthedrunk** [comment]
It's been reported to the mod dev. We will add the update when it comes out. 
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/748
