### ISSUE TITLE
Ticking entity crash when being shot by a skeleton archer

### ISSUE THREAD

**Issue by howradisit** [AllTheMods/ATM-5#117]
## Expected Behavior

Get shot by a skeleton

## Current Behavior

Game crashes

## Steps to Reproduce

1. Get shot by a skeleton
2. Game crashes

## Log

https://gist.github.com/howradisit/c87e3448bda1159a0dcdf1f33074de26

## Detailed Description

I encountered a skeleton and it shot me. I heard the shooting noise but the game immediately crashed.

**Comment by whatthedrunk** [comment]
This should be fixed in 1.25 let me know if its still an issue and we will reopen and let the mod dev know.
