### ISSUE TITLE
1.25 crash after the first entry into the game and kick from the server after a minute of the play

### ISSUE THREAD

**Issue by 1M0N3Y1** [AllTheMods/ATM-5#122]
this is crash report after first entry into the game
[crash-2020-05-17_17.58.06-client (2).txt](https://github.com/AllTheMods/ATM-5/files/4640483/crash-2020-05-17_17.58.06-client.2.txt)
this is what server write when i try to join and get kicked
[3.txt](https://github.com/AllTheMods/ATM-5/files/4640485/3.txt)

**Comment by whatthedrunk** [comment]
For the server crash it looks like it was fixed if you update Torch Slabs. Let me know if that worked out for you.

**Comment by whatthedrunk** [comment]
I added the change to 1.25a which is waiting on approval right now on Twitch. Let me know if you still have the issue after updating.
