### ISSUE TITLE
[1.25] Ticking entity crash when "super mobs" spawn with the allthemodium potion effect.

### ISSUE THREAD

**Issue by matthew-williams** [AllTheMods/ATM-5#123]
Ticking entity crash when "super mobs" spawn with the allthemodium potion effect. Crashes entire server. has happened through the last 4 versions, was hoping one of these updates would fix it.

## Expected Behavior
Mobs should spawn without the allthemodium potion effect.

## Current Behavior
A super mob spawns with what seems to be random potion effects

## Possible Solution
Remove allthemodium potion from possible potions mobs can spawn with.
 I cannot locate what mod is spawning them or how they get the potions, but I removed the allthemodium potion from the server and problem solved for now.

## Steps to Reproduce
Walk into a chunk with a super mob with that effect.

## Log
https://gist.github.com/matthew-williams/9c5b55d1ca34288029f4aabd46c7dbcb

## Detailed Description
Remove allthemodium potion.

**Comment by ghost** [comment]
I've got the same issue, consistently crashing about a minute after server start. Same stack trace

https://gist.github.com/Gwynnie/2fbadb914883c53a983fde79f8401fed

**Comment by whatthedrunk** [comment]
Let me know if changing this config works. 

config\apotheosis\apotheosis.cfg 
B:"Enable Deadly Module"=**false**

**Comment by whatthedrunk** [comment]
I added the change to 1.25a which is waiting on approval right now on Twitch. Let me know if you still have the issue after updating.
