### ISSUE TITLE
Refined Relocation Name Filter Crash

### ISSUE THREAD

**Issue by Athae1218** [AllTheMods/ATM-5#125]
## Expected Behavior
When using Refined Relocation's name filter option you should be able to list items to be filted through

## Current Behavior
Game crashes

## Steps to Reproduce
1. Place filtered hopper/Sorting Chest
2.Select filter options
3.Click Name Filter

## Log
https://gist.github.com/Athae1218/fdcec956c23dcccb4efc30a964cbcc41

## Detailed Description
A fix to the mod compatibility issue if there is one. My guess is likley JEI

**Comment by oly2o6** [comment]
bug for the mod developer, please make sure this is reported to their github
