### ISSUE TITLE
[1.25a] Excessive modded loot from mobs in the nether

### ISSUE THREAD

**Issue by xenoflot** [AllTheMods/ATM-5#127]
## Current Behavior

Been playing for about 8 hours today on a new world. Finally got to the nether just now. Shot a ghast with Power 4 vanilla bow, regular arrow, and it exploded into one tear and about 100 Reliquary "Catalyzing glands".  Curious.

Found some endermen, killed 2 of them and got 4 stacks of Reliquary "Nebulous Heart"s and two double-chests worth of Forbidden Arcanus' "Ender Pearl Fragments"

Quit to desktop and restarted the client. Killed 1 Large magma slime (and children) and got 47 Molten Cores. Killed 4 zombie pigmen and got nearly 2 stacks of Zombie Hearts. 

## Possible Solution

If it was just Reliquary items, or the "Luck" sword I made with Silent's, I might point a finger, but it seems to be wider than that. Vanilla loot such as zombie flesh and ghast tears are dropping normally.

## Steps to Reproduce

No idea, sorry. I just installed ATM5 yesterday, added Fast Leaf Decay and have played for about 8+ hours.

**Comment by vidiot5533** [comment]
This started happening with the most recent update, it didnt happen last week
