### ISSUE TITLE
[1.25a] Placement preview vertical offset incorrect for at least 2 mods

### ISSUE THREAD

**Issue by xenoflot** [AllTheMods/ATM-5#128]
Hi folks,

I've run into a problem where placement previews are showing lower than they should. I've encountered it with both Building Gadgets and Powah.

In this first image, I'm using the Building Gadget in default BuildToMe mode. As can be seen, I'm targeting a block on the shelf but the preview is showing about 1 and 2/3 blocks below where it should be.  https://i.imgur.com/Y4t7YDP.png

In this second image, I'm trying to place a Powah reactor on top of the dirt block and the preview is showing up below the dirt block. I've not used this mod before but I suspect that's supposed to be much higher. https://i.imgur.com/Vs2SBmK.png

I posted originally to the Building Gadgets git and they replied that they felt it wasn't their mod. The trouble with the Powah preview supports this.

My pack is as-supplied but for the addition of Fast Leaf Decay.

Cheers

**Comment by xenoflot** [comment]
Seems to have been caused by a bug in Vazkii's Neat. Fixed in 1.6-22. I'll close this ticket since I'm sure Neat will be updated when the pack updates.

**Comment by whatthedrunk** [comment]
Neat is not in ATM5
