### ISSUE TITLE
Silent Gear and reliquary

### ISSUE THREAD

**Issue by benbenlaw** [AllTheMods/ATM-5#132]
# Expected Behavior
<luck doesnt cause this many drops>

## Current Behavior
<adding luck to a silent gears tool causes a huge drop rate in relquary items -->

## Possible Solution
<maybe a relquary conflict in configs settings>

## Steps to Reproduce
>
1. add luck to a silent gear tool
2.kill a mob with it 
3 profit.
4.

## Detailed Description
<io belice its a drop rate issue with relquary maybe in config>

**Comment by masterbuck10** [comment]
This also happens with just looting 🤷

**Comment by P3pp3rF1y** [comment]
I had an issue logged for looting getting you a lot of drops in Reliquary and just retested with just Reliquary and definitely only getting Reliquary drop once I kill 4 mobs on average so this looks like there's some other mod in the pack that affects the drops.

**Comment by benbenlaw** [comment]
tried with just reluary adn silent gear bug not present another mod may be casuing it

**Comment by benbenlaw** [comment]
tried all the mods that are in all the mods 5 issue with defualt configs and was working fine.. Must be a config issue

**Comment by eliminat** [comment]
Does not appear to be only Silent Gear.
I'm using a Mystical Agriculture sword with Looting 3
Killed 2 bats, 4 stacks of batwings
2 enderman - 5 stacks of the ender fragments

On ATM5 v1.26

EDIT: Perhaps it is related to Silent Gear as it appears he's implemented a fix.
https://github.com/SilentChaos512/Silent-Gear/issues/129

**Comment by whatthedrunk** [comment]
We have the new versions of the mods in 1.27a that is pending approval. Let me know if you still have the issue. I killed a few things and it seemed normal.

**Comment by whatthedrunk** [comment]
Closing now but let me know if I need to open back up. Thanks.
