### ISSUE TITLE
ATM5 - v1.26 - Silent Gear Crimson Steel Hammer and Pick do not break blocks.

### ISSUE THREAD

**Issue by eliminat** [AllTheMods/ATM-5#139]
Video showing the issue: https://youtu.be/PWTBS0u0Xv0

Made a Silent Gear Crimson Steel hammer and pickaxe in 1.26
They don't seem to actually break blocks.
I'm unaware of any configuration that could cause this, and it's not spawn protection. Tested 11,000 blocks apart to verify not a location bug.

Quick Edit: this is a private server of myself and a single friend. Not a single-player instance. Have not yet verified in a single-player instance. WIll try when I have another free moment.

**Comment by Curlz242** [comment]
Yes, that is our problem too. Silent Gear (Obsidian-) Hammer, Shovel, Axe and Pickaxe does not break blocks except dirt and sand ....
(We are on a dedicated server  and it works for no one on it)

**Comment by whatthedrunk** [comment]
This may have been fixed before but just tested it in 2.5 that will be out sometime today and they work.
