### ISSUE TITLE
Rubber doesnt exist

### ISSUE THREAD

**Issue by Chriss122** [AllTheMods/ATM-5#140]
Hey,

we are using 1.25a

After hours of playing, we came to that point where we need rubber.

Creative Mode -> Rubber Sapling 
When the tree is grown, it becomes to an Oak Tree
And the Rubber Seed doesnt get me any items with botania.

Is it a bug, that Rubber trees are not existing ?
I mean, every Rubber Sapling becomes to an Oak Tree

Greetings

**Comment by Aphenon** [comment]
Industrial foregoing makes its rubber from the fluid extractor, place it next to any tree and it will make latex, which you can process to rubber.

**Comment by Chriss122** [comment]
maybe thats a workaround, but the main problem that rubber trees are not growing and the "normal" rubber cannot be earned is a problem.

**Comment by whatthedrunk** [comment]
That's the way IF works. IC2 and Tech Reborn were on the trees and if IC2 updates for Forge we will add it in to make them both work.
