### ISSUE TITLE
Unable to Export Milk from Refined Storage

### ISSUE THREAD

**Issue by OfficialStamper** [AllTheMods/ATM-5#141]
## Expected Behavior

Should be able to export milk from Refined Storage Fluids into; a tank or other fluid capacity vessel

## Current Behavior

Attempting to specify milk using a bucket of milk is not accepted as a filter in RS system.

## Steps to Reproduce
1.  Using the Rancher from Industrial Foregoing, milk cow(s)
2.  Send produced milk from Rancher into a tank (e.g. Mekanism Tank or DimStorage Tank)
3.  Use RS Importer, set to liquid, to import milk from tank into RS fluid storage disk.
4.  Attempt to export fluid milk from RS Fluid Storage, using either RS Exporter or Fluid Interface will not allow milk to be specified (using bucket of milk).

## Log
N/A

**Comment by UnjustCustos** [comment]
Had same issue. Simple work around is to craft a Big Bucket (two buckets in the crafting table). That will let you put milk in to the Export filter.
