### ISSUE TITLE
JourneyMap mod on the server causing clients to fail to connect

### ISSUE THREAD

**Issue by eliminat** [AllTheMods/ATM-5#142]
With ATM5 v1.26 clients had a very hard time connecting to the server.
Kept getting timeout errors with very little other information.
Clients kept hanging at the "Encrypting" stage then would eventually timeout. 
Tried to increase timeouts with the RandomPatches config to no improvement.
Wireshark capture showed normal traffic, then almost 30 seconds of no traffic, at which point server sent a FIN then RST packets.
Simultaneous capture showed there was clear communication both directions.
Neither client nor server were suffering for resources and were responsive.

## Possible Solution
Workaround found - remove JourneyMap mod from the server allowed clients to connect.
Did not need to remove the mod from client-side.
No change if clients connecting were Op or not.

Can attempt to collect and provide logs if requested, but need to know what would be useful. As mentioned, default logging did not capture anything useful.

**Comment by oly2o6** [comment]
We will remove journeymap from the server download in the next update if anyone gets anymore issues like this after the next update please let us know with a new issue
