### ISSUE TITLE
Issue connecting to 1.15.2  server. 

### ISSUE THREAD

**Issue by Tejasminer** [AllTheMods/ATM-5#143]
## Expected Behavior

This seems to be a 1.15.2 issue only. It does not affect everyone. 
I have been tring to figure this out for about a month. 
I was able to connect to our 1.15.2 pack and they updated something. 
Then I started having issues.

Same issues as the following.  
Mitsuma
#7039 Posted this. He basically did the same stuff as I.
https://discordapp.com/channels/254530689225981953/668264661539618816/716691627137302684

https://discordapp.com/channels/254530689225981953/668264661539618816/716665013162737676

I have tried the At launcher. 
I have no trouble connecting to a 1.5.1 server. 
Or any other version. 

## Current Behavior

When you connect it goes the encrypting screen and then just says failed to connect to the server. Disconnected. 

I will be more than happy to send you anything that may help. I know this is not really your packs issue I just don't know how to fix it.

## Log

Log from AT launcher.
https://paste.atlauncher.com/view/514ca911

## Steps to Reproduce

1.
2.
3.
4.

**Comment by whatthedrunk** [comment]
Let me know if removing Cyclic from your client and server fixes the issue. Getting reports on the discord about it and it seems to fix it.

**Comment by TheAxelum** [comment]
I can confirm that removing cyclic did seem to fix the issue for me. Thanks for the tip!

**Comment by eliminat** [comment]
The previously reported work-around for Journeymap on the server was more impactful for me, but with that removed, I now appear to be running into this issue as well. However, with this one, we're able to eventually connect after a few attempts.

**Comment by whatthedrunk** [comment]
I plan to remove Cyclic tonight or tomorrow to fix the issue. It will be added back once fixed. Thanks for the info everyone.
