### ISSUE TITLE
[1.27a] Server crash on new install

### ISSUE THREAD

**Issue by JulianGmp** [AllTheMods/ATM-5#144]
The newly installed server crashes, and gets into a restart loop.
## Expected Behavior
The server starts normally.

## Current Behavior
The server outputs a variety of exceptions, starts looping. I'm not sure if it's particular mod causing this issue.

## Possible Solution
N/A

## Steps to Reproduce

1. Download server files (`SERVER FILES-1.27a.zip`)
2. Execute `startserver.sh`
3.
4.

## Log
I uploaded the various logs to a [gist](https://gist.github.com/JulianGmp/1a6736ef569af244d7ee7c77c4bfd414).

Of note is the `overall.log`, which was generated with 
```sh
./startserver.sh > overall.log 2>&1
```
so it should show _everything_.

## Detailed Description

The server boot starts, at some point prints several errors, and after some time it prompts for a restart (seen at the very end of the `overall.log`).
Leaving it restart will result in the same situation, creating a loop.

In line 10223 and 10269 the server prompts that restart, maybe the output before those lines indicate the reason for the crash, I'm not sure on it though.

Noticable were quite many Exceptions related to Json parsing, for example starting at line 4740 in `overall.log`.

### OpenJDK Version in case it is relevant
```
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

**Comment by eliminat** [comment]
Only thing I saw there unusual was the actual error.

"java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)"
This means the tick took longer than it should have. May be a temporary issue on a new server if it's underpowered.

edit server.properties
change max-tick-time=-1
Save, try to start the server again.
This stops the protection for excessively long ticks, so be aware of that, but may let your server start and you in. 
If the ticks are that long though, the server may be slow once you're actually in. May want to compare your server specs with the recommended.

**Comment by JulianGmp** [comment]
>edit server.properties
>change max-tick-time=-1

Weirdly enough, this seems to have worked (kind of). 
It doesn't sit right though, I've run other modpacks on this machine before, without any major TPS issues. Even when generating terrain, I would never be near a single frame needing a whole minute to process.

This seems to be some sort of initialization, shouldn't they be executed before the first game frame?

---
Regardless, it seems to be a usable work around. Now my client is stuck on Encrypting, but I think that's unrelated to this (see #143).

**Comment by whatthedrunk** [comment]
Thanks for letting me know its related @JulianGmp 
I plan to remove Cyclic tonight or tomorrow to fix the issue. It will be added back once fixed. Thanks for the info everyone.
