### ISSUE TITLE
Request: Change Spaces in Folder Names within Simple Server Files .zip

### ISSUE THREAD

**Issue by OfficialStamper** [AllTheMods/ATM-5#146]
Just for us Linux boys, could I kindly request that the folder name within the Simple+Server+Files.zip does not contain spaces and are replaced with underscore or similar.

Muchus thanks <3

(picky I know, but if you use Linux terminal exclusively, you'll understand :))

**Comment by whatthedrunk** [comment]
Let me know is v2.1 works for you.

**Comment by OfficialStamper** [comment]
@whatthedrunk Sweet as a nut, thank you
