### ISSUE TITLE
2.0 - No recipe to craft minecraft:honey_block

### ISSUE THREAD

**Issue by OfficialStamper** [AllTheMods/ATM-5#147]
## Expected Behaviour
4 x honey bottles should craft 1 x honey block and show in JEI as such.

## Current Behaviour
Whilst honey block does actually show in JEI, there is no craft recipe, and if you attempt to craft in a default crafter (or any other crafter) using a 2x2 recipe of honey bottles, there is no output.

## Possible Solution
N/A

## Steps to Reproduce
N/A

## Log
N/A

## Detailed Description
N/A

**Comment by whatthedrunk** [comment]
I created a recipe using honey essence for the next update.
