### ISSUE TITLE
Workbench Plus Duplication Glitch

### ISSUE THREAD

**Issue by TheWooper** [AllTheMods/ATM-5#151]
## Expected Behavior
When you craft something in the Workbench Plus, you wouldn't expect to get the item automatically, and keep the materials used to make it.

## Current Behavior
When you place the required materials to make something inside of the Workbench Plus, select the recipe, and then press the 'Extract' button, you get the end product as well as the materials used to make it.

## Steps to Reproduce
1. Place the required materials for a recipe (in my experience, I was making the EnchantMover) inside the Workbench Plus.
2. Select the desired recipe (in this case, the EnchantMover).
3. Press 'Extract' in the bottom right corner of the Workbench Plus UI.
4. Acquire the materials and the end product.

It's worth noting I did have the Workbench Plus powered.

**Comment by oly2o6** [comment]
bug for the mod developer, please make sure this is reported to their github
