### ISSUE TITLE
Vile Dust uncraftable

### ISSUE THREAD

**Issue by cactusstyle** [AllTheMods/ATM-5#153]
## Expected Behavior
Placing soul sand into a device that can smelt should produce Vile Dust.

## Current Behavior
It produces Scoria from Create instead.

## Possible Solution
Using a crusher instead might be a better way to handle this without too much effort.

## Steps to Reproduce
1. Put Soul Sand into a furnace.
2. Wait for it to smelt.
3. Scoria comes out instead of vile dust.

## Detailed Description
Scoria is being produced when soul sand is being placed into a device that smelts instead of vile dust.  This prevents the creation of items needed to create Soul Shard Spawners.  Scoria is a block from Create that is a stone replacement block.  One solution I propose is to just have Soul Sand processed into a machine that grinds things into dust instead.

**Comment by whatthedrunk** [comment]
Added a recipe to turn Scoria into Vile Dust in the next update. Hopefully this update will be out soon I am just waiting on a Immersive Engineering update but for now you can add this to scripts/other/other_recipes.zs

`#Vile Dust and Scoria Fix
furnace.removeRecipe(<item:soulshards:vile_dust>);
craftingTable.addShapeless("soulshards_vile_dust", <item:soulshards:vile_dust>, 
               [<item:create:scoria>]);	   `
