### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by FOOTOOTOTOT** [AllTheMods/ATM-5#154]
I installed forge 1.15.2 with many different tutorials and kept on trying but nothing worked. I dragged it into my mods folder multiple times but it just didn't work. I quadrible checked everything and it says to mods loaded I open the mods folder put the .zip file and come back but it doesn't work please help me.

**Comment by whatthedrunk** [comment]
Dragged it into your mods folder? You should be using Twitch or MultiMC as they will download all the correct files for you.

**Comment by FOOTOOTOTOT** [comment]
I dragged it into the mods folder keep in mind I am a Mac user I tried to
install this mod (I downloaded the zip file put it in my mods folder then
loaded 1.15.2 forge but it didn’t work .
