### ISSUE TITLE
Pack Crash

### ISSUE THREAD

**Issue by Malavisto** [AllTheMods/ATM-5#158]
All the mods crashed after i updated it on the twitch launcher

Crash Report: https://pastebin.com/dYEyButV

I had 4G of ram allocated

 
![image](https://user-images.githubusercontent.com/52140990/84575832-7d85ee00-adb0-11ea-9086-869637eeb58c.png)
 

Pack Version:2.4

**Comment by whatthedrunk** [comment]
I can't replicate this but try with 5GB RAM and see if that helps. If not also try to update to version 2.5 that will be out later today.
