### ISSUE TITLE
Crash on menu on mods screen

### ISSUE THREAD

**Issue by Impos913** [AllTheMods/ATM-5#159]
## Expected Behavior

Was checking what mods there are.

## Current Behavior

Clicking on one of the mods crashed the game

## Steps to Reproduce

1.
2.
3.
4.

## Log

https://gist.github.com/Impos913/36c5c450a40cf7c43efb084067a2a768
crash report and latest.log ^

**Comment by whatthedrunk** [comment]
This seems to be fixed in my new 2.5 update I am working on. Let me know once you update if you are still having the issue.
