### ISSUE TITLE
Server forces BOP even when level type is default.

### ISSUE THREAD

**Issue by ChromeMystic** [AllTheMods/ATM-5#16]
I have set the Server to default but the Serverfiles result in a BOP world.
To Test feel free to use the same Seed on a singleplayer world and on a server world. This is the Server Properties I used.
`
#Minecraft server properties
#(File Modification Datestamp)
broadcast-rcon-to-ops=true
view-distance=10
max-build-height=256
server-ip=
level-seed=-1825852721
rcon.port=25575
gamemode=survival
server-port=25565
allow-nether=true
enable-command-block=false
enable-rcon=false
enable-query=false
op-permission-level=4
prevent-proxy-connections=false
generator-settings=
resource-pack=
level-name=world
rcon.password=
player-idle-timeout=0
motd=\u00a7eAll The Mods 5\u00a7r - Hosted by \u00a75ChromeMystic\u00a7r\nServer Pack Version: \u00a7a5-0.11
query.port=25565
force-gamemode=false
hardcore=false
white-list=false
broadcast-console-to-ops=true
pvp=true
spawn-npcs=true
generate-structures=true
spawn-animals=true
snooper-enabled=true
difficulty=easy
function-permission-level=2
network-compression-threshold=256
level-type=default
spawn-monsters=true
max-tick-time=60000
enforce-whitelist=false
use-native-transport=true
max-players=20
resource-pack-sha1=
spawn-protection=16
online-mode=true
allow-flight=false
max-world-size=29999984
`

**Comment by Revvilo** [comment]
Inside of your server, navigate to `config/biomesoplenty/` and open the `server.toml` file. This file makes it so that the `default` world type is always BOP for ease of use. Simply change the `use_world_type` setting inside there to `false`, then save the file, and the world will generate vanilla.
