### ISSUE TITLE
Smelting recipe conflict: Soul Sand

### ISSUE THREAD

**Issue by bill96012** [AllTheMods/ATM-5#160]
## Expected Behavior
Soul Sand only has one result in the smelting recipe.

## Current Behavior
There are three smelting recipe results for the Soul Sand, and will only get one of the three results.

Soul Sand can be smelt into:
- Scoria(Create)
- Soul Glass(Dark Utilities)
- Vile Dust(Soul Shards Respawn)

## Possible Solution
Change each result to other new recipes.

## Steps to Reproduce
1. Search `@minecraft soul sand` in the JEI
2. Click on the Soul Sand item from Minecraft
3. Switch to the `Smelting` tab
4. There are three recipe results for smelting the Soul Sand

**Comment by whatthedrunk** [comment]
This is fixed in 2.2 which will be out in 1-2 hours.
