### ISSUE TITLE
Chunk crash, Immersive engineering workbench

### ISSUE THREAD

**Issue by Xladomaz** [AllTheMods/ATM-5#161]
## Expected Behavior
1. Admin edits map and deletes the block causing issue

## Current Behavior
1. All helpers are afk and no response from administration  

## Possible Solution
1. Reason - Shift clicking the blueprint in the engineers worckbench
2. Delete the following block in mcedit or reset the chunk to last back uped version

## Steps to Reproduce

1. Place engineering workbench from the mod immersive engineering
2.Take any blueprint from the same mod
3.Shift click the blueprint in the bench slot
4. BOOM. chunk crash

**Comment by whatthedrunk** [comment]
This is fixed in 2.2 which will be out in 1-2 hours. If you are still crashing revert to a backup in the backup folder but the workbench will work after that.
