### ISSUE TITLE
A creeper with the AllthemodiumSight arrow effect exploded and left a lingering potion effect on the ground.  Walking into that circle crashed the entire server.

### ISSUE THREAD

**Issue by Arceaus98** [AllTheMods/ATM-5#162]
## Expected Behavior
(This was all discovered on accident)

A creeper took damage from an AllthemodiumSight arrow and exploded, leaving a large AOE of AllthemodiumSight potion effect lying on the ground (presumably because the arrows are made with Lingering potions).  Walking into the cloud should have given me 2:30 of AllthemodiumSight.

## Current Behavior
Instead of giving the expected potion effect, walking into the potion cloud crashed not just my client, but the entire server my friends and I were playing on.

## Possible Solution
I wish I knew...

## Steps to Reproduce
1.  Spawn an Arrow of AllthemodiumSight
2.  Spawn an Electric Bow (Mekanism)
     - Specific enchantments:  Power V, Quick Draw III, Endless Quiver (in that order)
3.  Spawn/find a Creeper, shoot the creeper with the AllthemodiumSight arrow
4.  Allow the creeper to blow up after being shot
5.  Walk into the resulting potion cloud

## Log
https://gist.github.com/Arceaus98/199cb1558c3c81d21a37995affc13507

**Comment by whatthedrunk** [comment]
This module should of been disabled. Are you using the correct configs for apotheosis?

**Comment by Arceaus98** [comment]
I'm not the server owner and I don't really know what the configs are supposed to be - can you expand on what the module is that you're referring to?

**Comment by whatthedrunk** [comment]
config\apotheosis\apotheosis.cfg
B:"Enable Deadly Module"=false 
Changing that should stop it from happening again.

**Comment by Arceaus98** [comment]
According to the server host, that module was already set to false.  Is there potentially another mod that could overwrite the setting regardless?

**Comment by whatthedrunk** [comment]
I actually read this wrong but it's basically the same crash I was thinking of. I'll pass the word onto the dev but if you need a fix asap the solution would be to revert to an older save and not use that arrow. If you can't do that you may have to edit your player save or remove it completely.

**Comment by Arceaus98** [comment]
We don't need a fix asap, no; I was able to rejoin the server after about fifteen minutes, although I had an absolutely horrendous-looking error screen while I was still blocked out.  Would having that image help at all, and if so should I paste it here or do something else with it?

**Comment by whatthedrunk** [comment]
Looks like this might not be fixable as we cannot remove the tipped arrow recipes because of the way vanilla works. So for anyone finding this issue the best solution is to just not make these arrows. The mod dev is also looking into other solutions and ill update if we find them. Thanks again for the report.
