### ISSUE TITLE
Placing the Alarm light / or siren hard crashes the game

### ISSUE THREAD

**Issue by Tiberias42** [AllTheMods/ATM-5#163]
## Expected Behavior

Place alarm, activates light/alarm when signaled via redstone

## Current Behavior

Attempt to place alarm, hard crash of game

## Steps to Reproduce

1. Make either Alarm Light or Alarm Siren
2. Place on any surface
3. ???
4. No profits, only crashes

## Log

https://gist.github.com/Tiberias42/6267419ea4297eab741b0891852d98c3.js

## Detailed Description

I would like to place alarms please, I want to make sure I don't blow up my pneumatic stuff

**Comment by Jamzs3** [comment]
LED lights also seem to crash for me

**Comment by stfwi** [comment]
Related issue: #173.

**Comment by whatthedrunk** [comment]
This will be fixed in the 2.5 update coming out later today thanks!
