### ISSUE TITLE
Mekanism digital miner filters not working 

### ISSUE THREAD

**Issue by punkrockpapa** [AllTheMods/ATM-5#164]
None of the ore* filters are accepted

## Expected Behavior
should set up new filter. Does nothing 

## Current Behavior
 does nothing 

## Steps to Reproduce
place digital ore miner, give power and storage, add new filter. Havent been able to get any to work but ore* is the main one i usually use

1.
2.
3.
4.

**Comment by punkrockpapa** [comment]
Just wanted  to let you know the manual filters (item stack & materials) work but you need one of every ore you want the machine to grab. The Tag selection is whats not working

**Comment by bill96012** [comment]
Maybe you should try "forge:ores" in the tag filter.
But also there are some ores that are not in the block tag.

**Comment by whatthedrunk** [comment]
Yeah like said above you have to now use the tag system.
