### ISSUE TITLE
Placing Pneumaticraft Programmable Controller Crashes Game

### ISSUE THREAD

**Issue by Trainerredstone7** [AllTheMods/ATM-5#165]
When a programmable controller is placed in a single player world, the game crashes. The world appears to still be playable when reloaded.

## Expected Behavior

Placing a programmable controller should not crash the game.

## Current Behavior

The game crashes.

## Steps to Reproduce

1. Enter a single-player world in ATM 5-2.2.
2. Place a programmable controller.
3. Observe that the game freezes and crashes.

## Log

https://paste.ee/p/BNIPJ

**Comment by oly2o6** [comment]
bug for the mod developer, please make sure this is reported to their github
