### ISSUE TITLE
while i'm pressing shift or ctrl i can't use numbers for switching items

### ISSUE THREAD

**Issue by TheYoloPanda** [AllTheMods/ATM-5#167]
I can [ctrl] or [shift] + [num] once, but it will not let me use shift or ctrl a second time. Same thing for Ctrl+Q for drop the entire stack.

I'm not the only one who has this problem: https://www.reddit.com/r/allthemods/comments/h84g0d/help_im_playing_the_atm5_and_while_im_pressing/

**Comment by whatthedrunk** [comment]
This seems to work for us on v2.3 that just came out. Let me know if it does then we can close it.

**Comment by TheYoloPanda** [comment]
Still having this issue

**Comment by TheYoloPanda** [comment]
All the Mods 5-2.4
Still having this issue
Can't figure out what  is causing this. I am still investigating

**Comment by OfficialStamper** [comment]
This also happens to me, in both Windows and Linux.  It works the first time you press, but subsequent presses do not work.
v2.4

**Comment by TheYoloPanda** [comment]
> This also happens to me, in both Windows and Linux. It works the first time you press, but subsequent presses do not work.
> v2.4

Yes this is the exact same issue that i have. Could you please tell me what keyboard and mouse are you using?

**Comment by OfficialStamper** [comment]
Razer Blackwidow Ultimate and Razer Mamba.  It's unlikely to be hardware or driver related tho, as there are no Razer Drivers for Linux.

**Comment by jbrualdi** [comment]
I'm also having this issue. I have a razer BlackWidow. I've tried unbinding everything from Ctrl and Shift but that doesn't work.

**Comment by TheYoloPanda** [comment]
v2.5 & v.2.6 still having this issue

**Comment by Revvilo** [comment]
Did the hard work and found that it is Pneumaticcraft Repressurized. Install that on its own and you'll have this problem.
