### ISSUE TITLE
Super drills Aren't craftable

### ISSUE THREAD

**Issue by Blindfoldedchaos** [AllTheMods/ATM-5#169]
Drill heads for super drills can't be crafted via silent gear or other methods.
## Expected Behavior

Should be able to make super drill heads for super drills mod

## Current Behavior

Currently can't make it

## Steps to Reproduce

1. Try to make the drill head or the silent gear blueprint

**Comment by whatthedrunk** [comment]
Tried adding the last of the recipes but now the mod is crashing. I will be removing it from today's update but will be adding the mod back once it is ready.
