### ISSUE TITLE
Kappa pick has 31516 damage

### ISSUE THREAD

**Issue by EJROBERTS011** [AllTheMods/ATM-5#171]
Kappa pick has 31516 damage

## Expected Behavior
For it to deal reasonable *normal* damage

Not one-shotting anything that doesn't have a damage cap

## Current Behavior

One-shots anything that doesn't have a damage cap and breaks all armor instantly (even supremum, not tested with indestructible)

## Steps to Reproduce
1. Create Kappa pick
2. Hit anything

## Detailed Description

Nerf this pick, it does too much dmg

**Comment by GenDeathrow** [comment]
I thought it was mistake, but the original mod developer set that number. There is a config option to either turn it off amd/or change the damage value. Which is insanely high. I may look in reducing it for its default damage. but you should be able to change the damage.

**Comment by whatthedrunk** [comment]
This is sort of fixed in the newest version. We just made a end game recipe for now.
