### ISSUE TITLE
Quark auto harvest and Nature's aura Crimson Meal conflict

### ISSUE THREAD

**Issue by mmis1000** [AllTheMods/ATM-5#172]
## Expected Behavior

The nether wart grows into a big mushroom

## Current Behavior

You harvested it

## Possible Solution

Disable auto harvest when you have Crimson Meal on hand.  
If not possible, disable auto harvest for nether wart (tested and it works fine for me)

## Steps to Reproduce

1. Right click on full matured nether wart with Crimson Meal on hand

**Comment by whatthedrunk** [comment]
Should work fine in 2.5 out later today.
