### ISSUE TITLE
Allthemodium Ore do not have forge:ores tag

### ISSUE THREAD

**Issue by mmis1000** [AllTheMods/ATM-5#176]
## Expected Behavior

It is a ore, so it should have `forge:ores` tag just like any other vanilla ore.

## Current Behavior

It only have `forge:ores/allthemodium`

## Possible Solution

Add the tag to it

## Steps to Reproduce

1. Open TMI and point mouse at it while hold shift to see what tag do it have

## Detailed Description

That cause miner mods that detect ore by whether it have `forge:ores` tag not works properly with it.

**Comment by whatthedrunk** [comment]
Allthemodium was made to not be automatically mined
