### ISSUE TITLE
SFM mod crashs my server ATM 5 version 2.4 

### ISSUE THREAD

**Issue by Uniform300** [AllTheMods/ATM-5#177]
Hi, been playing this world for 3 server updates now and haven't had an issue until now and now every time I open the Factory Manager from SFM mod then close the gui with either escape or the E key(using default keybindings except for crouch) at witch I instant get kicked and the server crash's with the following crash report in the [pastbin link](https://pastebin.com/6DLTKdn0) and after this started 6/20/2020, upon restarting the server then rejoin it that nigh, anytime I have the offending block I have 5 second game freezes every 3-5 mins until at random the server would crash again and I would have this happen 6 more times before getting off then I started playing again today and tried the block again thinking it was a glitch, it of course crashed the server witch here is the [link](https://pastebin.com/rNJ7abt3).

**Comment by whatthedrunk** [comment]
https://github.com/gigabit101/StevesFactoryManager/issues/102 here is the issue to follow.

**Comment by whatthedrunk** [comment]
You can manually update the mod now if you need to use it. This will be updated with the pack on the next update planned before the weekend.
