### ISSUE TITLE
Solar Flux Reborn (solarflux) encountered an error during the load_registries event phase

### ISSUE THREAD

**Issue by Skyridr** [AllTheMods/ATM-5#178]
Trying to create a server (freshly) made from ATM-5.. (2.4) But I keep getting:

> [23Jun2020 12:36:29.920] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
> net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
> 	Solar Flux Reborn (solarflux) encountered an error during the load_registries event phase
> §7null
> ]
> 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?]
> 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) ~[?:?]
> 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:995) ~[?:?]
> 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) ~[?:?]
> 	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]
> [23Jun2020 12:36:29.933] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /home/minecraft/serverfiles/./crash-reports/crash-2020-06-23_12.36.29-server.txt
> [23Jun2020 12:36:29.939] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
> [23Jun2020 12:36:29.939] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
> [23Jun2020 12:36:29.940] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
> java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
> 	at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:195) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1004) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:536) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:550) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:676) [?:?]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]

Is the mod Solar Flux Reborn broken?

**Comment by Endag** [comment]
Are you using Java 8 to run this pack? 
I've had similar problem on Debian 10 as by default it install Java 11

**Comment by whatthedrunk** [comment]
Yeah for some reason that is the only mod requiring Java 8 so either change Java to 8 or remove that mod for now. We are looking into maybe removing the mod in the next update just to have less issues.
