### ISSUE TITLE
Brown/Blue Glowstone crafting mismatch (involves Tiny Progressions and JAOPCA mods)

### ISSUE THREAD

**Issue by Arceaus98** [AllTheMods/ATM-5#179]
## Expected Behavior
I should be able to use brown glowstone dust to make brown glowstone, and blue glowstone dust to make blue glowstone (as well as the respective glowstone blocks).

## Current Behavior
Using the brown glowstone dust in a vanilla crafting table allows you to choose between brown or blue glowstone; however, all other crafting tables will only make blue glowstone with the brown glowstone dust.  The blue glowstone dust is currently useless in crafting.  

Additionally, the Block of Blue Glowstone from JAOPCA is textured as a Brown glowstone block instead of a Blue one.

## Possible Solution
Change crafting recipes to have the two dusts create their respective blocks.

## Steps to Reproduce
1.  Throw brown glowstone dust in a 2x2 crafting pattern - this will make blue glowstone
2.  Throw brown glowstone dust in a 3x3 crafting pattern - this will make a block of blue glowstone
3.  Throw blue glowstone dust in a 2x2 crafting pattern - nothing happens

**Comment by whatthedrunk** [comment]
Added a 2x2 blue glowstone recipe in today's update. Should be out within the hour.
