### ISSUE TITLE
Crafting ingots from nuggets with shift in Simple Storage Network

### ISSUE THREAD

**Issue by MWarsee** [AllTheMods/ATM-5#182]
## Expected Behavior

Craft ingots

## Current Behavior

Crushing game/server

## Steps to Reproduce

1. Puts nuggets in storage
2. Craft ingots using shift
3.
4.

## Detailed Description

I was using aluminium nuggets

**Comment by oly2o6** [comment]
bug for the mod developer, please make sure this is reported to their github
