### ISSUE TITLE
RFTools Utility Crafter deleting items when sorting inventory

### ISSUE THREAD

**Issue by mewitte** [AllTheMods/ATM-5#185]
## Expected Behavior
While in the Crafter from RFTools Utility, when I press the middle mouse button in my inventory, it gets sorted.

## Current Behavior
Instead of my inventory being sorted, it sorts the items into the Auto Crafter, placing items first into the recipe slots (deleting them in the process), then into the Crafters inventory. Those items then get lost when trying to pull them out again. I discovered this on a 2.4 server, also worked on 2.5 single player .

## Steps to Reproduce
1. Place a Crafter (any tier) from RFTools Utility
2. Open the GUI of the Crafter
3. Press the middle mouse button or the UI button for sorting
4. The items will be sorted, first into the recipe field, which then get deleted, then into the Crafters inventory

**Comment by whatthedrunk** [comment]
Thanks, I submitted the issue to the mod dev hopefully they can fix it and we can update.

**Comment by reo-ar** [comment]
Just updated the mod with a fix, regenerating config file will fix it once the jar is dropped in.

Further errors with inventories can be fixed by the invtweaks config file.
