### ISSUE TITLE
Simple Storage items getting placed into import/export cable upgrade slots

### ISSUE THREAD

**Issue by mewitte** [AllTheMods/ATM-5#186]
## Expected Behavior
When putting items in the Simple Storage Network, they should be placed into the available inventories.

## Current Behavior
Sometimes, items get placed into the upgrade slots of import/export cables. This also happens while upgrades are in those slots. The upgrades get placed back into the system. Changing the priority did not change this behavior.

**Comment by SQbuilder** [comment]
I am having the same problem

**Comment by oly2o6** [comment]
bug for the mod developer, please make sure this is reported to their github
