### ISSUE TITLE
Gold duping through apples

### ISSUE THREAD

**Issue by 0Bheka0** [AllTheMods/ATM-5#187]
Golden apples can be crafted with 8 gold nuggets and smelt down into 64 gold ingots.
__________________________________________________________
## Current Behavior
Golden apples can be crafted from 1 apple+8 nuggets/ingots/blocks.
This allows the user to make an apple with 8 nuggets and melt it down in bluepower alloy furance into 64 ingots.

## Possible Solution
Disable cheap apple recipes, correct alloy furnace recipe or accept that gold is free now.

## Steps to Reproduce
1.Craft golden apple with nuggets
2.Stick into either blue power alloy furnace.
3. Cycle it.
4.Profit

**Comment by whatthedrunk** [comment]
Thanks! This should be fixed in the next update, if you are on a server make sure to update the scripts folder and bluepower config.
