### ISSUE TITLE
Industrial Foregoing Block Placer not placing blocks

### ISSUE THREAD

**Issue by mewitte** [AllTheMods/ATM-5#188]
## Expected Behavior
When provided with power and logs, I expect the Block Placer to place the block on the block placing side.

## Current Behavior
The Block Placer does play the sound of the block being placed, but it doesn't place the block.

## Steps to Reproduce
The video was taken on a server running version 2.4:
https://imgur.com/a/cUSVKRP

## Detailed Description
I want to use the block placer to place a log in front of a fluid extractor to automate latex gathering.

**Comment by mmis1000** [comment]
Did you allow the fake player to change the terrain in the ftbchunk setting?

The default is banning all fake players as far as I know.

**Comment by oly2o6** [comment]
make sure its all reported to the mod developer as this would not be a bug on our side, however it might have already been fixed
