### ISSUE TITLE
Lightest lamps machine does not allow auto input, mod update avaliable

### ISSUE THREAD

**Issue by mmis1000** [AllTheMods/ATM-5#189]
The Lightest lamps machine does not accept auto input (like hopper)

## Expected Behavior

It accepts input through hopper, mekanism pipes... etc

## Current Behavior

It does not.

## Possible Solution

Update to latest version of lightest lamps

## Steps to Reproduce

1. place a gas centrifuge ob ground
2. place a hopper on it
3. throw some glow stone into hopper

## Detailed Description

 The issue is already fixed in latest version of Lightest lamps
https://github.com/DcZipPL/lightestlampsmod/issues/10

**Comment by whatthedrunk** [comment]
Thanks, new update will be out today.
