### ISSUE TITLE
JournyMap Waypoint Creation Title Not Highlited Automatically

### ISSUE THREAD

**Issue by jbrualdi** [AllTheMods/ATM-5#191]
The best way I can describe the issue is; when I create a waypoint using JourneyMap it automatically sets the title as (<Zpos>, <Zpos>). In older versions this title would be automatically highlighted so I can change the name without having to select the default title, then delete it. This is a very minor issue for sure, but I create a lot of waypoints, so this is a sort of quality of life thing for me.

**Comment by oly2o6** [comment]
this would be something to report to the mod developers to see if they will change it back
