### ISSUE TITLE
Cooking Table from Cooking for Blockheads fails to craft some items

### ISSUE THREAD

**Issue by snydej** [AllTheMods/ATM-5#192]
Despite having the necessary ingredients and the cooking table saying that it is craftable, attempting to craft certain items instead results in a stack trace getting printed to the log. I've reproduced it on completely fresh worlds many times now and it always seems to affect different food items and even vanilla food items. Which food items are affected change when you exit and reopen the word even if you don't close Minecraft.

## Expected Behavior
When you have the required ingredients to craft something, clicking twice on the icon for what you want to craft in the Cooking Table should craft it.

## Current Behavior
The first click on the Apple Pie icon changes the tooltip to say "Click again to craft" and the second click does nothing visible in-game but prints a stack trace to the logs (sometime the stack trace is not printed but the item still doesn't craft. I don't know why). Closing and reopening the word will change up which items do and do not craft.

## Steps to Reproduce
1. Create a new world. (optional, the test worlds that I made were all Creative Mode, Superflat with Structures off, that I put into peaceful) 
2. Give yourself a Cooking Table and a bunch of ingredients, for example a stack each of wheat, cocoa beans, bowls, beetroots, brown mushrooms, red mushrooms, sugar, pumpkins, and eggs.
3. Make sure you're in Survival Mode
4. Place the Cooking Table down and open it's GUI.
5. Try to craft all the different food items that ought to be craftable with just a vanilla crafting table (i.e. not the ones that require a furnace). You'll probably notice that several of them will not craft.
6. If, somehow, none of them failed, exit and reopen the world and repeat step 5.

## Log
The stacktrace printed when a craft fails:
https://gist.github.com/snydej/7e21ed18ddb387f3ac6f111e9eceacc2

**Comment by oly2o6** [comment]
CWB bug, please make sure this is reported to their github
