### ISSUE TITLE
Potions Master Ore Sight Potions not Functioning Properly

### ISSUE THREAD

**Issue by jbrualdi** [AllTheMods/ATM-5#194]
The ore sight potions, from Potions Master are supposed to let you see ores in a certain range through blocks.
However, they only work briefly, and in certain angles. The potions are definitely very powerful, so I would suggest a change in the recipe if the bug can be fixed, especially for the Allthemodium Ore Sight Potion, which I've tested and does kind-of work.

**Comment by whatthedrunk** [comment]
This will be fixed in the next version that will be out in the next 5 hours. Thanks for the report.
