### ISSUE TITLE
Allthemodium's Yield Can Be Increased by a factor of 9

### ISSUE THREAD

**Issue by OneLemonyBoi** [AllTheMods/ATM-5#195]
Usually, when you smelt Allthemodium, you get 1 nugget. When you mill it using create and then smelt it, you get 1 ingot.
## Expected Behavior
It gives 1 nugget.
## Current Behavior
It gives 1 ingot.

## Possible Solution
Change the recipe to give 1 nugget.

## Steps to Reproduce
Look at recipe in JEI

**Comment by mmis1000** [comment]
Isn't the crusher of create designed to yield more output than simply smelt it?
All recipes of create crusher have x1 ~ x6 (randomly) output than smelt it using vanilla furnace. (except glowstone)
Otherwise, what it the point to setup such complex machine to process an ore?

**Comment by OneLemonyBoi** [comment]
Both the crusher and the mill can do this, and the mill is painfully easy to set up, only requiring 10 minutes of tinkering. And not all recipes have that x1 ~ x6 multiplier. Most ores are x1 ~ x2. Along with that, Allthemodium is supposed to be a rare ore for endgame items, and most items only require a few nuggets.

**Comment by whatthedrunk** [comment]
I have a fix for this in the new version thanks for the report! It should be out within 5 hours.
