### ISSUE TITLE
Attempting to highlight an inventory with Steve's Factory Manager crashes the game.

### ISSUE THREAD

**Issue by snydej** [AllTheMods/ATM-5#196]
When configuring a Factory Manager there is a feature to highlight an inventory in-world to help you make sure you've selected the right inventory. Attempting to use this feature crashes the game.

## Expected Behavior
The selected inventory becomes visibly marked in the world.

## Current Behavior
The game crashes.

## Steps to Reproduce
1. Place down a Factory Manager and a chest adjacent to it.
2. Open the Factory Manager's GUI.
3. In the top left there are some buttons. Click on the second button. It should have the tool tip "Item Interactions".
4. Select "Input" from the menu.
5. Click the arrow on the right edge of the newly created input element to expand its configuration options.
6. Click the arrow to the right of the "Inventories" item to expand this subcategory.
7. Right click on the chest icon and select "Highlight in world". This will crash the game.

## Log
https://gist.github.com/snydej/303d8285a85c061d7a8d8b98ebbcb72a

**Comment by snydej** [comment]
After trying to use this mod I am convinced that the author never played with it themselves. The UI has constant glitches, settings seem to change randomly, connecting modules doesn't work reliably, deleting modules often crashes the game, etc... I looked up this mod and it's only in alpha. It's clearly not ready to be in a pack. I have had no end of trouble with this pack and I can tell that the longer I keep with it the worse it's going to get.

**Comment by oly2o6** [comment]
yeah alot of mods are alpha right now so if you want to make sure all this is reported on their github it would help out alot for us and them
