### ISSUE TITLE
Allthemodium configuration file

### ISSUE THREAD

**Issue by BlackflyCanada** [AllTheMods/ATM-5#199]
I'm wondering if there's a change we could get an AlltheModium configuration file?

I'm trying to keep my private server updated regularly, and myself and the players on my server are consistently having to adjust our setups for maximizing the amount of ATM ore we find. I totally understand the purpose of this ore as a gate to prevent finishing endgame to quickly. However myself and my players are somewhat frustrated with the rapid changes and would appreciate the ability for me to configure the mod to match our play and needs. Thanks, any help in this regard is greatly appreciated.

Also, we are experiencing an 'internal server error' when the ATM sight potion expires. Causing a disconnect.

Thanks. I am somewhat new to server hosting, so if I'm missing something here, any pointers would be appreciated as well.

Thanks.

**Comment by oly2o6** [comment]
if we were to add a configuration file it would be in atm6 now as atm5 is minor updates only, sorry i cannot offer more assistance
