### ISSUE TITLE
Crash when changing Mipmaping to 1

### ISSUE THREAD

**Issue by mProjectsCode** [AllTheMods/ATM-5#201]
## Expected Behavior
Change the Mipmaping level and the game changes it.

## Current Behavior
Change the Mipmaping level and the game crashes.
(For me it was the first boot-up of the modpack after installation)

## Possible Solution
Reason: java.lang.NullPointerException: Rendering overlay

## Steps to Reproduce
1. Install the pack via twitch
2. open it up
3. go to settings
4. change the mipmap level

## Log
[crash-2020-07-15_17.17.51-client.txt](https://github.com/AllTheMods/ATM-5/files/4926195/crash-2020-07-15_17.17.51-client.txt)

**Comment by oly2o6** [comment]
if anyone else has this issue in the future please comment on this post and i will reopen it but i assume its a one off thing for you as ive not heard of this or anyone including myself experiencing it
