### ISSUE TITLE
crash on crafting blocks

### ISSUE THREAD

**Issue by matthewvs59** [AllTheMods/ATM-5#205]
## Current Behavior

when shift clicking blocks from the crafting table into my inventory (witnessed with mekanism tin and IE copper) from a vanilla crafting table it hard crashes the game

## Steps to Reproduce

1. go to a vanilla crafting table
2. fill it with ingots
3. shift click the block
4. crash

## Log

https://pastebin.com/cZadG3gr

**Comment by whatthedrunk** [comment]
looks like this might be fixed but if not please report here so we can get it updated for you. https://github.com/TheIllusiveC4/Polymorph/issues
