### ISSUE TITLE
[2.12] Not able to craft wither skull from wither fragments

### ISSUE THREAD

**Issue by Blackcatz1911** [AllTheMods/ATM-5#209]
## Expected Behavior
Able to craft the wither skull

## Current Behavior
Not able to craft the skull
https://cdn.discordapp.com/attachments/668264661539618816/736866084661231616/unknown.png

## Steps to Reproduce

1. Take 9 wither skull fragments
2. Try to craft the wither skull
3. Wither skull cannot be crafted

**Comment by whatthedrunk** [comment]
fixed in today's update
