### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by benserwa** [AllTheMods/ATM-5#21]
Haven't done thorough testing on these, but I have installed them all in a pack at the same time that has booted into a world for a little while, I got as far as punching some trees without anything crashing or breaking.

https://www.curseforge.com/minecraft/mc-mods/ama-damage-indicator
https://www.curseforge.com/minecraft/mc-mods/ceiling-torch
https://www.curseforge.com/minecraft/mc-mods/classic-bars
https://www.curseforge.com/minecraft/mc-mods/client-tweaks
https://www.curseforge.com/minecraft/mc-mods/customquests
https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl
https://www.curseforge.com/minecraft/mc-mods/essentials
https://www.curseforge.com/minecraft/mc-mods/good-skeletons-dont-strafe
https://www.curseforge.com/minecraft/mc-mods/respawnable-pets
https://www.curseforge.com/minecraft/mc-mods/serene-seasons
https://www.curseforge.com/minecraft/mc-mods/speedy-ladders
https://www.curseforge.com/minecraft/mc-mods/stronghold-compass
https://www.curseforge.com/minecraft/mc-mods/time-travel-mod
https://www.curseforge.com/minecraft/mc-mods/water-erosion

**Comment by whatthedrunk** [comment]
https://github.com/AllTheMods/ATM-5/issues/1
