### ISSUE TITLE
New Server Files Installing has an extra "h" in the https

### ISSUE THREAD

**Issue by bsteckroth** [AllTheMods/ATM-5#210]
## Expected Behavior

Line 28: https://media.forgecdn.net/files/3016/274/All+the+Mods+5-2.13.zip

## Current Behavior

New Server Files Installing has an extra "h" in the https

Line 28: hhttps://media.forgecdn.net/files/3016/274/All+the+Mods+5-2.13.zip

## Steps to Reproduce

1.
2.
3.
4.

**Comment by whatthedrunk** [comment]
Oh wow thanks for letting me know! New files should be approved soon.
