### ISSUE TITLE
Dupe glitch when upgrading Colossal Chests

### ISSUE THREAD

**Issue by jayschuster** [AllTheMods/ATM-5#211]
## Expected Behavior
The chest should either drop all the items on the floor and upgrade, or retain its inventory and upgrade.

## Current Behavior
It drops all the items on the floor, and retains its inventory, effectively duplicating all items within.

## Possible Solution
Temporarily disable Colossal Chests until the mod developer fixes the issue

## Steps to Reproduce
1. Create a wooden Colossal Chest with 1 Interface (only tested with Wood-->Copper)
2. Create a Chest Upgrade Tool
3. Obtain 2 Copper Chest Walls, 1 Copper Chest Interface, and 1 Copper Chest Core
4. Right click the upgrade tool on the Colossal Chest with the Copper parts in your inventory
5. Collect all the dropped items, and put them back in the Colossal Chest

## Detailed Description
Temporarily disable Colossal Chest mod until the issue is fixed.

**Comment by oly2o6** [comment]
can you make sure this is reported to the mod developer, we cant exactly disable the mod as people will have items already stored in them so we would need this solved quickly

**Comment by jayschuster** [comment]
I reported to the devs, they responded about a week ago and put it in #todoOn Aug 5, 2020 20:18, oly2o6 <notifications@github.com> wrote:
can you make sure this is reported to the mod developer, we cant exactly disable the mod as people will have items already stored in them so we would need this solved quickly
