### ISSUE TITLE
Crash: Nether Quartz Bees

### ISSUE THREAD

**Issue by Thunder-Nova** [AllTheMods/ATM-5#214]
## Expected Behavior

Shouldn't crash

## Current Behavior

Crash (idk how to properly explain this)

## Steps to Reproduce

1.
2.
3.
4.

## Log

[My crash report](https://gist.github.com/Thunder-Nova/d36d8ef01190a6108815291b00ee1466)
[Superp Crash report](https://gist.github.com/Thunder-Nova/ae4318f45f260e9a26a8a30ae400a7a9)

**Comment by whatthedrunk** [comment]
fixed in today's update
