### ISSUE TITLE
Server Files Malware: Heur.BZC.ONG.Leopard.1.41E93A41

### ISSUE THREAD

**Issue by IcyJalapeno** [AllTheMods/ATM-5#215]
Download the Server File and Extracted

## Expected Behavior

Being able to download and not have BitDefender flag it and delete it automatically.

## Current Behavior

Item path | Threat Name | Action taken
...\Local\Temp\SIMPLE-SERVER-FILES-2.16.zip=>SIMPLE-SERVER-FILES-2.16/startserver.bat | Heur.BZC.ONG.Leopard.1.41E93A41 | Deleted

## Possible Solution
Correct whatever is causing the false positive.

## Steps to Reproduce
1. Have BitDefender installed
2. Download Server Files of Twitch App or Modpack's Website

**Comment by whatthedrunk** [comment]
Not sure there is anything we can do about a false positive with your computer. Feel free to share here if you want. https://github.com/BloodyMods/ServerStarter/issues
