### ISSUE TITLE
Cant install All the Mods 5-2.16b

### ISSUE THREAD

**Issue by DerMoki** [AllTheMods/ATM-5#218]
## Expected Behavior

Cant install All the Mods 5-2.16b with Twitch Launcher

## Current Behavior

Here is the Screenshot of this Issue:
https://ootpic.de/images/2020/08/10/Ge8s.jpg

## Steps to Reproduce

1.
2.
3.
4.

**Comment by MaGGuS3206** [comment]
Same here, other Error:

https://i.gyazo.com/0a2617ddef27ee24b1ea00018196222d.png

Can't update via Twitch-Launcher

**Comment by EvilKingStan** [comment]
Same here. Update in twitch launcher to newest 2.16b and fails because of:
Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 289310 in database. Aborting installation.

**Comment by darbubu** [comment]
Same problem here. Sometimes that error code and also sometimes other things like: Unable to get Addon: Ropes Mod! (358557) - File ID: 2888934

**Comment by shiro-42** [comment]
That problem is related to twitch and is the same for every modpack, as a workaround you can use another launcher like multimc

**Comment by whatthedrunk** [comment]
should be working now
