### ISSUE TITLE
Cant Connect, Fresh install

### ISSUE THREAD

**Issue by AlexUnknown37** [AllTheMods/ATM-5#219]
Trying to connect to the server just gives me a disconnect.
Current version 2.16b, Reinstalled twice now, Using GDLauncher.
![Zw5LlLogKH](https://user-images.githubusercontent.com/17447099/89842965-0e1c4880-db2c-11ea-972b-f7bc145fc5b4.gif)

**Comment by whatthedrunk** [comment]
there was an issue where gd was downloading the wrong files while twitch was broken. Make sure your client mods are the same as the server. Twitch is working again if you want to try it there.
