### ISSUE TITLE
GLFW error 65539: invalid key 4

### ISSUE THREAD

**Issue by Shad0wyDr3ams** [AllTheMods/ATM-5#22]
everytime i try to launch all the mods 5  via the twitch launcher it throws the error GLFW error 65539: invalid key 4 listed i have checked my graphics drivers to make sure they are updated and they are the latest nvidia drivers as of current date.
this never happened until the latest update for allthemods5 which is V1.4
when i use V1.3 this issue does not appear at all for me

**Comment by whatthedrunk** [comment]
Let me know if its still happening with the current version and we can reopen it.

**Comment by midvightmirage** [comment]
I get it in my own vanilla plus modpack im trying to do but as a GL render error
it seems that minecraft does not like the mouse forward side button being set as a keybind
i did here b ecause this is all i found about this error
