### ISSUE TITLE
Mouse sensitivity

### ISSUE THREAD

**Issue by Osgz11** [AllTheMods/ATM-5#23]
Fresh download from Twitch app. Mouse is super sensitive. When I turn down the sensitivity in order to move and play at a pace I can handle and I click into a chest or a crafting table it is slow.

**Comment by Revvilo** [comment]
The ingame sensitivity slider only effects the player looking around, not the mouse cursor itself. Are you using the windows setting or maybe one from a peice of mouse software?

**Comment by Osgz11** [comment]
Yes I guess I was =\ lol sorry for the inconvenience
