### ISSUE TITLE
Server keeps timing out players and crashing - Started out of nowhere

### ISSUE THREAD

**Issue by DubstepHippo** [AllTheMods/ATM-5#24]
The server I made was working perfectly without any crashes or issues for around a week with a few players on it at a time. Yesterday a new issue appeared where the Java Minecraft server window would become unresponsive and it would time out the players and not resume response. I had 4gb of ram allocated and increased it to 6gb with no real difference in time to crash. 
Here's a log from when it was working fine and not crashing. 
[2020-02-19-10.log.gz](https://github.com/AllTheMods/ATM-5/files/4232223/2020-02-19-10.log.gz)

And here's the debug logs from the crashes. It doesn't seem to pump out errors before the time out. 
[debug-5.log.gz](https://github.com/AllTheMods/ATM-5/files/4232218/debug-5.log.gz)
[debug-4.log.gz](https://github.com/AllTheMods/ATM-5/files/4232219/debug-4.log.gz)

**Comment by whatthedrunk** [comment]
let me know if you are still having issues on the newest version. If so give me pastebin files of the logs if you can or hit up up on this discord to chat about it.
