### ISSUE TITLE
Can't see JEI

### ISSUE THREAD

**Issue by Vany** [AllTheMods/ATM-5#25]
allthemods 5 1.6

but i removed biomesoplenty

here is no JEI on screen
nothing interesting in logs
i can configure controls, but everything is not workinng.

**Comment by CrankySupertoon** [comment]
Try Hitting Ctrl + O

**Comment by Vany** [comment]
no, controls of jei not working too

**Comment by Vany** [comment]
i found fresh installation works well, problems begins when i remove biomesoplenty
