### ISSUE TITLE
Nether Portal Loop

### ISSUE THREAD

**Issue by figori** [AllTheMods/ATM-5#29]
Once upgrading to 1.6, it appears that traversing a Nether portal puts you in a loop until you end up dying.

**Comment by Quu1337** [comment]
Do you have jetpack equipped? take it off before entering portal.

**Comment by figori** [comment]
No jetpack.  This is on a server, not hosted local to me.  And I haven't tested this in SPS.

**Comment by figori** [comment]
But it happens even if you're in creative mode.

**Comment by MacsimusPrime** [comment]
Hi!
I can confirm this. It happens to me in ATM5 v. 1.14
@figori did you have a Portal Charm from cyclic on you? Cause this started to happen after I equipped the portal charm. Removing the charm didn't resolve it and also for me this behavior happened even when I am in creative.
Maybe the portal charm changes the portal cool down by mistake

**Comment by figori** [comment]
No charm.  Couldn't figure out what was causing it, but I know in 1.12 it went away.  Also haven't seen the issue in 1.15 either.
