### ISSUE TITLE
Sleeping in bed

### ISSUE THREAD

**Issue by Jerbearjerry** [AllTheMods/ATM-5#3]
When trying to sleep in a bed at dusk, the chat says  " Respawn point set " " New spawnpoint has been set!" 

https://i.imgur.com/dBl8zFf.png

**Comment by DietmarKrause** [comment]
as far as i know this is new in vanilla 1.15: https://www.minecraft.net/en-us/article/minecraft-1-15-pre-release-1 see 

> CHANGES IN 1.15 PRE-RELEASE 2
Tweaked chunked loading performance calculations
Setting the respawn point by using a bed now shows a message
Added stats for anvil and grindstone interaction counts
Fixed bugs

**Comment by MelanX** [comment]
There must be a mod which adds this feature. Maybe Morpheus.

**Comment by whatthedrunk** [comment]
Let me know if you are still having this issue on the newest version and ill reopen.
