### ISSUE TITLE
GLFW error 65539: invalid key 4

### ISSUE THREAD

**Issue by Yes-dad** [AllTheMods/ATM-5#32]
every time i go to launch the mod pack it crashes giving me the error: GLFW error 65539: invalid key 4
the game launched fine the first time launching after install but second time i get this same error, tried re-installing and it did the same thing, worked once and then proceeded to give me the error again

**Comment by DietmarKrause** [comment]
same here since atm Vers 1.8 and newer. 1.7 workes fine. I can always start the pack once, after that i get the above error, too

**Comment by DietmarKrause** [comment]
after severeal retries i got a different error. Has to do soemthing with mekanism ; https://pastebin.com/xxakUeDh

**Comment by DietmarKrause** [comment]
i found the problem: it is the ingame definition of contol-keys. The pack doesnt like the extra-mouse buttons of a gaming mouse any more. I have a logitech mouse with extra buttons. As long as i dont define one of these keys ingame everything is ok. I had defined mouse button 5 for sprinting which was fine up to pack Version 1.7. From 1.8 on the pack cannot be loaded anymore if you try to load an old world: you can start it once and play. But if you start to restart the pack after that, the pack will crash with the above error. The key definitions seem to be global that means not part of the world, so the pack crashes on start. Is there any work around for this ? can the control keys be set to standard or can i delete the definition of this mouse button manually somehow?

**Comment by Yes-dad** [comment]
This would make a lot of sense as I always link my crouch and vein mine onto my mouse, so I suppose until there is some fix for this I’ll have to switch up my key-binds

**Comment by DietmarKrause** [comment]
realted: https://github.com/AllTheMods/ATM-5/issues/22

**Comment by oWave** [comment]
Alternative workaround: Delete `mouse.4`, `mouse.5` and any other offending keys if more mouse buttons cause issues too, from `options.txt` in your instances folder. That will reset those actions to the default keybind and allow you to load the pack and rebind the key just fine.
You'll have to do this every time you load the pack until a fix is released.

**Comment by DietmarKrause** [comment]
Thank you for that info ! Very helpful. I will do that from now on.
