### ISSUE TITLE
[FULL][1.10] Mekanism reactor 

### ISSUE THREAD

**Issue by Heroeskitchen** [AllTheMods/ATM-5#33]
When loading the new server from an upgraded version, the system warns about missing tritium and deuterium.  Also, the rotary condensetrator is fully broken, it will no longer convert lithium to gas nor water to water vapor.

**Comment by DraconicMyx** [comment]
any idea when the update to mekanism 9.9.16.408 will be inthe pack still cant use the rotary cond to convert lithuim

**Comment by whatthedrunk** [comment]
Let us know how its doing not that mekanism is in beta. If anything is still broken we can report to them.
