### ISSUE TITLE
Smelting Soul Sand

### ISSUE THREAD

**Issue by Rixhephtos** [AllTheMods/ATM-5#34]
Hi there, while trying to make some Vile Dust (Soul Shards Respawn), I noticed that by smelting Soul Sand, I was getting Soul Glass (Dark Utilities). It seems both the Vile Dust and Soul Glass use the same recipe- smelting Soul Sand. I haven't been able to get any Vile Dust, I keep getting Soul Glass.

![2020-03-09_10-24-57](https://user-images.githubusercontent.com/61978807/76222116-8040d800-61f0-11ea-9c14-4a67bc67e15d.png)

**Comment by Flatlinez** [comment]
i can confirm, have same problem

**Comment by DerSoftwerker** [comment]
Confirmed, same here in 1.13

**Comment by oly2o6** [comment]
will be fixed this week, update with the change should be out friday ish
