### ISSUE TITLE
ATM 1.10 @Mekanism pipes issue

### ISSUE THREAD

**Issue by AlexTeplyh** [AllTheMods/ATM-5#36]
Hi!

After the update, I noticed that pipes are disconnected from the electrolytic separator and they won't connect if I try to reinstall the pipe or separator itself

!!! UPDATE !!!
Rotary condensentrator is not working as well

**Comment by whatthedrunk** [comment]
Mekanism is now in beta in the new version and a lot of these issues are fixed. If you are still having issues let me know and we can report to mek.
