### ISSUE TITLE
ATM 1.7 World became corrupted due to Nature's Aura

### ISSUE THREAD

**Issue by WillisShek** [AllTheMods/ATM-5#37]
> Time: 2020/3/10 下午 8:47
> Description: Exception in server tick loop
> 
> java.lang.ClassCastException: de.ellpeck.naturesaura.blocks.BlockDecayedLeaves cannot be cast to net.minecraft.block.LeavesBlock
> 	at net.olafkeijsers.fastleafdecay.FldScheduler.tick(FldScheduler.java:55) ~[?:v20] {re:classloading}
> 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
> 	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}

Environment: self-hosted with Windows 10. No custom mods or modifications are made to the server files.

After using the aura a lot and tons of damage were caused, like blocks were destroyed and all living creatures died, I planted a few ancient trees. After a few minutes, the world becomes corrupted and no player could log in again. The only way to "fix" our server is to remove Nature's Aura. Even after the trees are removed due to the removal of the mod, adding the mod back afterward will crash the server again.

**Comment by DietmarKrause** [comment]
try to remove fast leave decay and leave Natures Aura. There is a problem with fast leave decay and Natures aura. The ancient trees leave decay in a different way and this is not compatible with fast leave decay
https://github.com/Ellpeck/NaturesAura/issues/78

**Comment by DietmarKrause** [comment]
https://github.com/Ellpeck/NaturesAura/issues/78

**Comment by WillisShek** [comment]
Thanks
