### ISSUE TITLE
ATM 5 Water Condensator From IndustrialForegoing 

### ISSUE THREAD

**Issue by SinisterCow** [AllTheMods/ATM-5#38]
Water Condensator not picking up water when placed next to a source block. Not sure if its a Modpack issue or the mod itself.
![Capture](https://user-images.githubusercontent.com/62122490/76577357-67a81a80-649b-11ea-9892-f1a53a688a9a.JPG)
![2Capture](https://user-images.githubusercontent.com/62122490/76577385-85757f80-649b-11ea-9e57-ca327fb7604d.JPG)
![3Capture](https://user-images.githubusercontent.com/62122490/76577395-8dcdba80-649b-11ea-83aa-5e4180781131.JPG)

**Comment by Flatlinez** [comment]
was having same issue so i am using mekanism pump instead only needs 1 water source block under the pump

**Comment by thatParadox** [comment]
I have also had this issue

**Comment by LTNightshade** [comment]
Already fixed : 
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/711
