### ISSUE TITLE
Storage Drawer mod dont keep locked drawers content.

### ISSUE THREAD

**Issue by Uniform300** [AllTheMods/ATM-5#40]
So found an issue that if u put any amount of any item into any locked drawer from the storage drawer mod then empty the drawer of said Item ether by hand or and auto sorting system the drawer will clear the item after any amount of time other users say they had this occur without unloading the chunk of the drawer but I have only seen it after un/reloading said drawer.

**Comment by ovingiv** [comment]
I have seen this issue when I was first starting up my server. I found that as long as I keep one item in each drawer I don't run into that as it's a ui glitch.

If you find that too annoying to deal with like me, get into refined storage.

Best of luck!
