### ISSUE TITLE
client side crash with cyclic charms

### ISSUE THREAD

**Issue by Flatlinez** [AllTheMods/ATM-5#41]
i have been having a problem through a few updates now. Any time i have a cyclic charm on me and it is triggered it crashes mc client side everytime. both charms i tested are fire and antidote. is this happening to anyone else, i figured it would be a common problem so i did not post before.

**Comment by thatParadox** [comment]
I have also had this with the fire charm from cyclic

**Comment by whatthedrunk** [comment]
They seem to be working now thanks!
