### ISSUE TITLE
Server files for 1.11 missing [was: JEI recipes not working]

### ISSUE THREAD

**Issue by mbrucher** [AllTheMods/ATM-5#42]
I started the world on 1.5, at the time where we had the recipe book icon.
Now, we have JEI, but clicking on JEI doesn't show a recie, nor does hitting the configured key (r) to show the recipe even if I check that it's the only one configured with this key.
Server started with java -Xmx4000M -Xms3000M -jar minecraft_server.1.15.2.jar nogui, but how do I make sure that the server really loads all the mods?

**Comment by mbrucher** [comment]
Also just tried to craft a 1x2 drawer on the 1.11 server, but the crafting table doesn't work. The 1x2 drawer shows up in JEI (but no recipe available).

**Comment by mbrucher** [comment]
Silly me, forge.jar; not the minecraft_server.1.15.2.jar.

**Comment by mbrucher** [comment]
Actually forge.jar fails to start with
[ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found
So still aproblem or misisng launch instructions.

**Comment by mbrucher** [comment]
Looks like it's due to SolarFlux? But then 1.11 client is not compatible with 1.10 and there is no 1.11 server package :(

**Comment by mbrucher** [comment]
@whatthedrunk Haven't seen once someone trying to actually address the issues. Is there a point in having a GitHub project?

**Comment by whatthedrunk** [comment]
Update to 1.15 and see if the issue persists. If so we need actual logs.

**Comment by mbrucher** [comment]
Well, I stqrted plqying on 1.11, not 1.15, and upgrading the server to 1.12 or 1.13 meant loosing some oreslike JAOPCO or forbidden arcanus, so I can't try 1.15.
SolarFluxReborn is still crashing during init, and I can provide the log if requested (I noticed this also on 1.12 and 1.13 when I noted the issue with JOAPCO and fobidden arcanus).
