### ISSUE TITLE
server files missing

### ISSUE THREAD

**Issue by nightsniper31** [AllTheMods/ATM-5#43]
I have tried to update my server but can't download the server files/modpacks they don't seem to be there anymore can someone help please happened after the new update the other day.

**Comment by Flatlinez** [comment]
i just read the update notes and downloaded the forge server from forge and transferred the new files to server from my client worked like a charm https://adfoc.us/serve/sitelinks/?id=271228&url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.15.2-31.1.19/forge-1.15.2-31.1.19-installer.jar
