### ISSUE TITLE
Industrial Foregoing Dissolution Chamber prod. 2 Range Upgrade for 1 set of items

### ISSUE THREAD

**Issue by LTNightshade** [AllTheMods/ATM-5#46]
Industrial Foregoing Dissolution Chamber prod. 2 Range Upgrade for 1 set of items
with using 2 Buckets of Latex.

## Expected Behavior
Produce 1 Item

## Current Behavior
produces 2 Items

## Possible Solution
?

## Steps to Reproduce
1. Put 2 buckets of Latex into Maschine
2. put in 2 Redstone, 2 Glass Panes, 4 (ex.) Lapis
3. Wait for 2 Items to produce
4. Profit...

## Detailed Description
ATM 5 - 1.12
Forge - 31.1.25
Industrial Foregoing - 2.2.2

**Comment by NillerMedDild** [comment]
This issue has been reported on the IF issue tracker here: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/730
Looks like it's fixed :)

**Comment by whatthedrunk** [comment]
Good to know it will be fixed soon thanks for the link!
