### ISSUE TITLE
Multiple types of copper

### ISSUE THREAD

**Issue by JonStryker** [AllTheMods/ATM-5#47]
Hallo!

Currently there are three types of copper in the game: From Mekanism, Silent's Mechanism and Blue Power. The first two of these I already found by randomly mining ores. 

Would be best if those mods were made compatibly so that there is only one type of ore that all three use.

**Comment by whatthedrunk** [comment]
This should be fixed in new checks as of a long time ago. If you see any duplicates in new areas let me know what you find and I will fix. Thanks!

**Comment by redaktiv** [comment]
I only find Mekanism Copper Ore in my world but there are some problems in 1.17

Smelting Mekanism copper ore in a silent mechanism furnace gives you mekanism copper ingots
Smelting mekanism copper ore in a mekanism smelting factory gives you silent gear copper ingots. 
The same goes for mekaniskm copper dust. 

A mekanism copper ingot gives you silent mechanism copper nuggets.

And last. 9 copper ingots from mekanism or silent mechanism gives you a silent mechanism copper block BUT if you but copper ingots in a compacting drawer from Storage drawers it gives you the ingot you put in (mekanism or silent mechanism), silent mechanism nuggets and Blue power blocks.
