### ISSUE TITLE
Apotheosis broke sugar cane and bamboo texture

### ISSUE THREAD

**Issue by Quu1337** [AllTheMods/ATM-5#5]
Apotheosis broke sugar cane and bamboo texture, the leaves(?) on bamboo end-bits are white and not transparent like they should be.

**Comment by Shadows-of-Fire** [comment]
Forge bug: https://github.com/MinecraftForge/MinecraftForge/pull/6452

**Comment by whatthedrunk** [comment]
Looks like forge was able to fix it and once I update the pack to 1.15.2 this week we should be good.
