### ISSUE TITLE
xNet Facade breaking the conectors

### ISSUE THREAD

**Issue by RayMorgenstern** [AllTheMods/ATM-5#50]
## Expected Behavior

Facade should hide the xnet connectors

## Current Behavior

The facade hides the connector indeed but at the same time isolates it from the multiblock structures and breaks the connections, and breaks the channel se-up too 

## Steps to Reproduce

1. Place a connector
2. Mimic a surface with a Facade
3. Apply the facade on the networking cable

**Comment by oly2o6** [comment]
bug for the mod developer, please make sure this is reported to their github
