### ISSUE TITLE
Can no longer access server world upon entering the ender "dragon portal"

### ISSUE THREAD

**Issue by dpcollier128** [AllTheMods/ATM-5#52]
Upon entering the "end-of-game" portal (the one which activates after slaying the ender dragon), I find that my server's world throws an "Internal server error" (without anything descriptive as to why or what the error may have been) upon attempting to render terrain or some such

## Expected Behavior
I expected the usual "conversation of gods" text scene to start so it may be skipped

## Current Behavior
No such scene occurs, and I am kicked back to the server list upon clicking the "Confirm" button on the error screen

## Possible Solution
I found that modifying my character's NBT data for what location he's at in the world (back to a more stable position in the overworld at home) completely alleviates this error at least until the next time I attempt to enter the dragon portal

## Steps to Reproduce
1. Kill the ender dragon (likely using a Silent Gear crossbow and several pieces of heavily enchanted armor including an Iron Jetpacks emerald jetpack, Mekanism free runners, and a couple of Cyclic crystalized obsidian armor pieces, and I mean REALLY heavily enchanted, up to the point where you need 250 levels or so to apply the last book at an anvil for some. I cheat. Sue me)
2. (optional?) Scare the dragon egg off the portal and collect it (using a piston or whatever)
3. (optional?) Say "nah, ima go explore" and toss an ender pearl into one of those bedrock-encased, floating portals nearby the giant obelisks so you can explore the outer reaches of the end (I found an ender city, pillaged the place, and took all their fruit. Was fun. Might come back with an RFtools builder to quarry it all out or something later)
4. Come back to the dragon portal somehow (I used a JourneyMap waypoint as an OP on my server, but this had unexpected results as I got stuck in the ground and nearly suffocated to death at first. I had to teleport away to the overworld with ANOTHER waypoint and return to the end for this penultimate step. Which I think is another bug in itself, waypoint-teleporting between dimensions?)
5. Attempt to enter the dragon portal and... profit? (DO make backups of your world folder beforehand and/or know-how to alter your player data with something like NBT Explorer so you can fish yourself out of the error-filled abyss to relative safety)

## Log
I don't believe this constitutes a crash as both my server and the game client didn't shut down as a result of experiencing this error. Although, it did make any current iteration of my world inaccessible until performing some NBT black magic to get back to the overworld

## Detailed Description
See all the above points under "steps to reproduce" for a far more detailed -- and VERY stream of consciousness style -- description of the events leading to this error for me

In the end, this error hasn't been entirely game-breaking to me. I can't watch the "final scene" of the game, but at this point, I've done this successfully more than ten times in different packs from mc 1,10.0 up to current. It's just a minor inconvenience as I roll back some backups or manually change my character's NBT data

**Comment by whatthedrunk** [comment]
This seems to have been fixed or at least I cannot reproduce it. Let me know if its still broken on the newest version and I can try some more.
