### ISSUE TITLE
Recipe conflict: Oak chest - Minecraft Chest

### ISSUE THREAD

**Issue by redaktiv** [AllTheMods/ATM-5#53]
Oak Chest from Quark share recipe with standard minecraft chest. If this is intended then some crafting recipes needs the minecraft chest like link cables from simple network.

**Comment by Ceillian** [comment]
This issue is preventing the trash can from being crafted.

**Comment by oly2o6** [comment]
fixed in fridays update but for the meantime try throwing different types of wood together to get the chest recipe to not see the recipe as "oak_chest" as the vanilla one accept multiple woods to make it, the quark does not
