### ISSUE TITLE
AVG Antivirus has found malware within the Securitycraft jar file and thus quarantines it

### ISSUE THREAD

**Issue by dpcollier128** [AllTheMods/ATM-5#56]
## Expected Behavior
Securitycraft should be completely clean of malware

## Current Behavior
AVG Antivirus quarantines the Securitycraft jar and prevents the game from starting up properly as a result with this mod installed

## Possible Solution
Leave the mod quarantined or outright uninstalled from the pack's profile in the Twitch launcher

## Steps to Reproduce
1. Have AVG free edition installed
2. Startup the Twitch Launcher
3. Startup All The Mods 5 modpack for Minecraft
4. See that AVG has found malware within Securitycraft

## Log
No crash log found. Minecraft client throws an error to the effect of "unable to find expected mod jar" or some such

## Detailed Description
Seeing as Securitycraft isn't one of the major mods I actually use, leaving this one out of my profile of the pack seems to be the best bet for keeping things clean. I have no idea if the virus AVG scanned is a false positive or not, but it's better to be safe than sorry

PS: I'm updating my Java just to be certain it's secure

**Comment by someaddons** [comment]
https://www.virustotal.com/gui/file/88e3b1df475e5c896356f0abd65f646f0f714da0b47e3e714cbe32181bf3aed1/detection
Seems to be just your antivir acting up

**Comment by dpcollier128** [comment]
Okay. I figured as much. Maybe this virus is sneaking into the mod through Java itself? I don't know. I'll see what I can do about shutting AVG up about it or something.
