### ISSUE TITLE
AFK return, Quantum entangloporter and chest disappeared, digital miner not working, cannot be restarted

### ISSUE THREAD

**Issue by Swallowtail23** [AllTheMods/ATM-5#57]
## Expected Behavior

Come back from AFK, and digital miner still working...

## Current Behavior

Return from AFK, Digital miner is silent, and the chest on the back and the quantum entangloporter have both visually disappeared. Replace them and the miner still will not fire up, and replacement QE seems to come in with memory of old one (i.e. full of energy even though new device newly placed). Despite this, the miner will not show its screens, and will not therefore start, although can be configured. 
Remove and resite the miner, setup again - no change, still not working. 

Has happened twice.

## Steps to Reproduce

1.
2. Can give access to server if needed.
3.
4.

**Comment by Swallowtail23** [comment]
If I reload from an earlier save the QE is still there, but after an hour or so AFK the issue repeats. This is in the logs when the world loads from the save, with QE still there:

```
[01Apr2020 11:04:28.531] [Server thread/INFO] [Mekanism ChunkManager/]: Loading 0 chunks for dimension minecraft:the_nether
[01Apr2020 11:04:28.558] [Server thread/INFO] [Mekanism ChunkManager/]: Loading 505 chunks for dimension minecraft:overworld
[01Apr2020 11:04:28.961] [Server thread/WARN] [Mekanism ChunkManager/]: Block at BlockPos{x=-661, y=77, z=865} was does not support Anchor Upgrades?! Block: minecraft:air
```

And a lot more like that. I have an anchor upgrade in the digital miner.

It is my server, so i have logs available etc. For now I have removed the digital miner. Interestingly the digital miner ran for 2 days (real-time) with no problems, it's just overnight last night that this has happened, and again today after reload.

**Comment by whatthedrunk** [comment]
Since this issue Mekanism has moved from Alpha to Beta. Let me know if you still have the issue.
