### ISSUE TITLE
Auto Sort causes items to be placed into incorrect slots on RFtools crafter, results in Deletion of items.

### ISSUE THREAD

**Issue by omnivance** [AllTheMods/ATM-5#58]
Modpack version ATM5 1.14

## Expected Behavior
Middle-Clicking to sort inventory should organize my player inventory, leaving the Crafter inventory/UI alone.

## Current Behavior
The Auto-sort treats the 3x3 crafting grid of the Crafter as valid inventory, and places up to 9 items there. Attempting to remove them, as the crafter uses it as a blueprint and does not actually hold items there, they are deleted upon any attempt to retrieve them.

## Possible Solution
The crafter's slots seems to have been acting funny the whole time, so it might be an RFtools issue.
However, this was not present before the addition of Quark and it's auto-sort in 1.14

## Steps to Reproduce
1. Have items in your inventory
2. Interact with the "Crafter" from RFTools
3. Middle-click to sort
4. Note items placed in the recipe slot, and that you cannot remove them without item loss.

## Log
No log to share, nothing visible in server client to report

## Detailed Description

**Comment by iridiumlynx** [comment]
Similar bug can be reproduced with Project Table (Blue Power) and Crafting Station (Silent Gear). Either Inventory Sorter or Inventory Tweaks Reborn (or both) sorts the crafting pad.

**Comment by whatthedrunk** [comment]
next update uses a new sorting mod that seems to fixed refined duping. Let me know if you have any issues when 1.16 drops later today thanks!
