### ISSUE TITLE
Can't craft Trash Void (Cyclic) or Trash can (Quantum Storage)

### ISSUE THREAD

**Issue by Sim-ian** [AllTheMods/ATM-5#59]
## Expected Behavior
The chest required is listed as a Minecraft Chest but when crafting a chest it becomes a Quark chest which is not accepted in the recipe for either of the trash cans.

## Current Behavior
As the chest all seem to be converted to Quark, the Cyclic and Quantum Storage recipe requires a Minecraft Chest.

## Possible Solution
Possibly an Ore Dictionary issue.

## Steps to Reproduce
1. Make a chest, Oak, Spruce Or Birch (the ones i have tested)
2. Try to craft either the Trash Void (Cyclic) or Trash can (Quantum Storage)

## Log
Not Required

## Detailed Description
See Above
Pack Version: 5-1.14

**Comment by Quu1337** [comment]
You can make vanilla (oak) chests by crafting "vertical planks" and using them to craft chest, kinda workaround.
