### ISSUE TITLE
Sorting a Refined Storage Pattern Grid results in output items being duped into the Upgrade slots

### ISSUE THREAD

**Issue by OttoWerse** [AllTheMods/ATM-5#60]
I'm sorry if this is a duplicate, I just wanted to report this quickly, as it's quite a game-breaking bug in my eyes.

## Expected Behavior

If the "sort inventory under mouse" key is pressed in a pattern grid, nothing should change, as there is nothing to be sorted in any way.

## Current Behavior

When something is in the "output" section of a Patter Grid from Refined Storage and the sort button is pressed, the imaginary items in the output section formate into real items and are placed in the upgrade slots at the top of the GUI

## Possible Solution

Removing the GUI of the Pattern Grid (or actually all Refined Storage Grids) from the list of sortable inventories should resolve this without causing any other problems.

## Steps to Reproduce

1. Place an Allthemodiuum Block in the output of a Pattern Grid
2. Press the "Sort inventory under mouse" Key once
3. Now you have two Allthemodium blocks
4. Repeat until infinity

**Comment by whatthedrunk** [comment]
next update uses a new sorting mod that seems to fixed refined duping. Let me know if you have any issues when 1.16 drops later today thanks!
