### ISSUE TITLE
Changing the colour of a canvas bag delete every item in it. 

### ISSUE THREAD

**Issue by redaktiv** [AllTheMods/ATM-5#62]
## Expected Behavior

When changing the colour of a blue power canvas bag it should keep it's inventory. 

## Current Behavior

When changing the colour of the bag it deletes it's inventory. 

## Steps to Reproduce

1. Craft a white canvas bag from Blue Power
2. Put anything into the bag
3. Combine the bag with a dye in the crafting grid
4. Now you have a canvas bag of that colour but with an empty inventory

**Comment by oly2o6** [comment]
changing the colour of a bag wipes the inventory, its how most bags work from all mods, not really a bug just how its made
