### ISSUE TITLE
Mystical Agriculture Recipe Conflicts 

### ISSUE THREAD

**Issue by chubes1** [AllTheMods/ATM-5#63]
There are still a few conflicts that i have found on my server so i thought id let you know:

Chicken Essence: Feathers and Raw Chicken are the same layout 
Nature Essence: Potatoes and Carrots are the same layout
Wood Essence: Jungle Log and Dark Oak Log are the same layout

**Comment by whatthedrunk** [comment]
Fixed in 1.16 that should be out later today.
