### ISSUE TITLE
Cant see block i'ds or key binding for it.

### ISSUE THREAD

**Issue by JORDZIE** [AllTheMods/ATM-5#67]
please tell me which mod it is and how to fix it. thanks

**Comment by Quu1337** [comment]
F3+H to see item tags in JEI
`/theoneprobe config ` for seeing stuff you point at

**Comment by JORDZIE** [comment]
Thank you very much for ur reply but that is not solving it that just is changing style and halready have advanced tooltips on :)

**Comment by JORDZIE** [comment]
got it you need the PROBE ONE ITEM AT THE START THANKS!
