### ISSUE TITLE
can't increase the chunk load number

### ISSUE THREAD

**Issue by eric1194** [AllTheMods/ATM-5#68]
it is currently set to 25 on the server and I can't find where to change that setting. I try following these but without any luck. "https://forum.feed-the-beast.com/threads/ftb-utilities-how-to-increase-allowed-claimed-chunks.220348/" & "https://www.reddit.com/r/feedthebeast/comments/8wui2b/ftb_utilities_chunk_loading_question/".

## Expected Behavior
there should be a config somewhere to increase the number of allowed chunk load per user and or OP

## Current Behavior
I can't fin any config file, or even creating my own doesn't work

## Steps to Reproduce
Load the server and after opening FTB chunk load you will see that chuck load permitted is set to 25

**Comment by Quu1337** [comment]
`worldname/serverconfig/ftb_chunks.toml` or something very close to it, most serverside configs are stored there in 1.15.2 and it confuses me too much.

**Comment by eric1194** [comment]
Awesome, I just try and it work.
Thanks,
