### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by HugeLol556** [AllTheMods/ATM-5#69]
A block from Refined Storage and an inventory sorting mod that I am not clear on are interacting in such a way that creates an easy and fast duplication glitch.

The block is the Disk Drive.

The icon for the sorting mod is a small gray square on the right side with an image of an arrow pointing down and the letters A and Z.

## Steps to Reproduce
1. Place a disk drive from Refined Storage down
2. The disk drive has two sections of slots, a horizontal row of 9, and two vertical columns of 4.
3. Place any items in the horizontal row. The items won't actually be placed there, rather an "image" of the item will be there for other purposes of Refined Storage. This item cannot be taken out, it will simply disappear when interacted with.
4. On the right of the row is the icon for sorting. Click it and all items in the horizontal row will be placed in the vertical columns.
5. These vertical columns can be interacted with and the items can be taken out by the player.
6. Repeat indefinitely

## Issue/Solution
I noticed another post with the same issue using a different block from Refined Storage. It seems that whatever the inventory sorting mod is doing is overriding/ignoring the fact that the "fake" items that Refined Storage has in its slots shouldn't be interacted with and is putting them in locations where the items can be taken by the player. I think this may be an issue that the inventory sorting mod should be made aware of.

**Comment by TheLonelyKid159** [comment]
thanks

**Comment by whatthedrunk** [comment]
next update uses a new sorting mod that seems to fixed refined duping. Let me know if you have any issues when 1.16 drops later today thanks!
