### ISSUE TITLE
Pls add Mod Ender Hopper or Ender Storage

### ISSUE THREAD

**Issue by rlcold** [AllTheMods/ATM-5#71]
https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8

https://www.curseforge.com/minecraft/mc-mods/ender-hopper

**Comment by Quu1337** [comment]
https://github.com/AllTheMods/ATM-5/issues/1

Both of those mods are for minecraft 1.12, modpack uses 1.15.2 making it pretty much impossible to add them.

**Comment by rlcold** [comment]
We need a teleport mod for simpler items like the old Teleport Pipe T.T RIP
