### ISSUE TITLE
ATM5 version 1.16a server

### ISSUE THREAD

**Issue by RedChaos56** [AllTheMods/ATM-5#72]
i made a server with ATM5 version 1.16a when i try to join it i get this error
failed to synchronize registry data from server

**Comment by Sim-ian** [comment]
Have you added any mods to the client but not added to the server or vice versa?

**Comment by darkluzer** [comment]
This was happening with a friend that didn't update his client correctly

How to fix:
1. Delete everything in your all the mods client folder (be sure to backup)
2. Download the new client (make sure to use 1.16a)

**Comment by whatthedrunk** [comment]
Let us know if you are still having issues. You can try 17a as well to see if that helps.
