### ISSUE TITLE
Please add Uranium to Uraninite Conversion or Uraninite Seeds via Mystical Agriculture

### ISSUE THREAD

**Issue by Redlotus99** [AllTheMods/ATM-5#73]
I would love to see a more renewable source for Uraninite from Powah. 
Currently there is no way to create or replenish Uraninite as there is not recipe for or it.

An easy fix would be to create a Uranium to Uraninite conversion or have Mystical Agriculture seeds for Uraninite. This would prevent the need to only mine Uraninite.

A more detailed description would be to have a more solid solution for producing Uraninite other than just mining.  Adding a conversion for 2:1 or 1:1 Uranium ingots from Silent's Mechanism for Uraninite  might be feasible. It may also be viable to have Mystical Agriculture include a recipe for Uraninite seeds so that it can be grown as most other ingots are.  

I have added a conversion in Crafttweaker that should do the job, but it would be nice to see this added officially if warranted.

**Comment by whatthedrunk** [comment]
I added scripts to convert your seeds or essence and on todays update 1.25a added uraninite.
