### ISSUE TITLE
Bed bounce when trying to sleep at night

### ISSUE THREAD

**Issue by cbredlow** [AllTheMods/ATM-5#75]
## Expected Behavior

Bed should remain motionless when sleeping in them.

## Current Behavior

Beds jitter up and down. Tried with empty inventory, and it still occurred 

## Steps to Reproduce

1. Upgrade to 1.16a
2. Select any bed placed prior to the pack update
3. Rightclick on bed
4. Bounce

**Comment by Sim-ian** [comment]
This also seems to cause issues with villager farms, they now seem able to use the beds a trampolines and escape their enclosures.

**Comment by someaddons** [comment]
its fixed with a performant update to 2.06m

**Comment by whatthedrunk** [comment]
Yeah like someaddons said its fixed if you update performant. This will be updated in 1.17!
