### ISSUE TITLE
Cannot generate lost cities world

### ISSUE THREAD

**Issue by TheInfamousAlk** [AllTheMods/ATM-5#77]
Hi, I have a freshly installed ATM5 version 1.16a. No mods added or removed manually, no manual config tweaks, just a fresh install. 

When I try to make a lost cities world (by clicking lost cities on the top right, setting it to any profile, then clicking done), it generates a world without lost cities. I have tried the default world type, biomes o' plenty, caverns, and amplified and none generates lost cities. I have also tried the "all cities" profile in lost cities config UI just to make sure I'm not missing them, and no cities generate. 

And yes, the other world types work fine, the BOP stuff generates properly, etc. 

Any idea what's wrong?

**Comment by whatthedrunk** [comment]
It looks like a possible issue with BOP and Lost Cities. You can try removing BOP to see if that works for you and if not we will make sure to update the mod ASAP when it updates. https://github.com/McJtyMods/LostCities/issues
