### ISSUE TITLE
Crashing Before World Even Loads

### ISSUE THREAD

**Issue by Kluber52** [AllTheMods/ATM-5#78]
## Expected Behavior
<I would expect the world to load normally. However, it has not loaded since the latest update download. I did backup but I'm hoping I can figure out what's wrong and fix it. However, I'm going through the crash report and I can't figure out what's going on with it. After the update it did say that there was an issue with being unable to get lag goggles and one inventory tweaker. >

## Current Behavior
<However, I'm going through the crash report and I can't figure out what's going on with it. After the update it did say that there was an issue with being unable to get lag goggles and one inventory tweaker. Some of the time it crashes without even completely booting. Others I try to select my only world and it won't load.>

## Steps to Reproduce

1.
2.
3.
4.

## Log

<https://gist.github.com/Kluber52/18b3c3639589b3e3f4713bd224e1c935>

**Comment by whatthedrunk** [comment]
Let me know if you get this on a new profile with the newest version. Lag Goggles was never in the pack and Inventory Tweaks Reborn was removed a little while back for some issues. If it still happens reopen this issue with a new log if you can. Thanks!
