### ISSUE TITLE
ATM5 1.16a Server not working

### ISSUE THREAD

**Issue by Nagafuchi01** [AllTheMods/ATM-5#79]
## Expected Behavior

It should load the server with the ATM5 1.16a version

## Current Behavior

At the beginning of the gui server loads 20 lines aprox and closes inmediately

## Steps to Reproduce

1.Download modpack from the twitchc launcher
2.download forge installer 31.1.44 as the modpack runs in this version
3.run the forge installer
4.run the server
5.emula=true
6.add mods from the modpack downloaded from twitch app
7.server crashes after the server gui gets on screen 2 seconds
8.if i took out the mods it runs normally

## Log

[crash-2020-04-17_11.13.08-server.txt](https://github.com/AllTheMods/ATM-5/files/4494133/crash-2020-04-17_11.13.08-server.txt)

## Detailed Description

I just want to keep playing the modpack getting updated cause of the errors of some mods that are in alpha

**Comment by whatthedrunk** [comment]
It doesn't look like all the mods are downloaded. Try running the server files again as twitch was having issues yesterday. 17a is out now as well if you want to just try that one.

**Comment by Nagafuchi01** [comment]
If I run the server with 0 mods on the folder it runs with no problem or crash, dont understand why it does crashes with mods while in the client it works fine
