### ISSUE TITLE
Something in 5-1.17b has changed Supremium Flight

### ISSUE THREAD

**Issue by Sim-ian** [AllTheMods/ATM-5#84]
Something has changed the functionality of the Supremium armour flight, previously once flight was initiated you stayed in flight mode till you either touched the ground or double tapped space to end flight mode. Since updating to 1.17b whenever you change what you have in your hand either using the scroll wheel of a hot key number the flight mode is disabled plummeting you to the ground, water or lava

## Steps to Reproduce
1. initiate flight with Supremium armor and flight augment
2. change weapon or tool in hand

**Comment by whatthedrunk** [comment]
This has been fixed in version 18 coming out within the hour.
