### ISSUE TITLE
Lost Everything

### ISSUE THREAD

**Issue by PrettyLudde** [AllTheMods/ATM-5#85]
I came back from the mining dimension and all of my chests and it contents were gone. I had all my mekanism machines in the same place and they are all gone to. Except one of the solar panels and one cable. Seems like a whole chunk got reset or something. Had my bed in close vacinty to it. I closed the game while in mining dimension yesterday and when i loaded in today i suffocated in a wall respawning in mining dimension and that might have caused it. Not that interested in playing more now but still. Better to post the issue.

**Comment by whatthedrunk** [comment]
Thanks for the issue and sorry it happened to you. I assume this was a rare issue as I have not had anyone else report it but if you have more information please let us know.
