### ISSUE TITLE
JEI trouble loading

### ISSUE THREAD

**Issue by PeacefulBunny** [AllTheMods/ATM-5#86]
## Expected Behavior

Updated to 1.18...
JEI has trouble loading in existing save games.
Loaded a saved game(world) but the JEI was missing. Tried another saved world from the previus patch but the problem persisted. NO "ctrl+o" does not solve the issue.
Made a new world and the JEI reappeared. Closed the new world and loaded the old save game and the JEI reappeared there aswell.
If you shutdown minecraft you need to follow the same steps to gain the JEI in the older save.

Hope it makes sense. Let me know if you need a log or something.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by whatthedrunk** [comment]
Still not sure what is causing this but adding the notes on how to fix it on the changelog. Hopefully with more users we can track down what is causing it as I cannot reproduce it.

**Comment by hadeedsarfaraz** [comment]
@whatthedrunk i know forgecraft was having this issue a while ago so you should see if you can message some people there

**Comment by PeacefulBunny** [comment]
@whatthedrunk do you have a list of which mods you updated for version 1.18 so I can disable them one by one. Maybe I can find the troublemaker :)

I found these threads: 
https://github.com/mezz/JustEnoughItems/issues/1684
https://github.com/SilentChaos512/Silent-Gear/issues/52
It was a multiplayer error tho. Still i did check the silent gear mod, disabled it, but the problem remains.

**Comment by whatthedrunk** [comment]
We were able to update everything that needed an update. After we found out about that error I went back to the older version and updated 1 at a time to try and reproduce it but could not.

**Comment by PeacefulBunny** [comment]
Found it. It's the bonsai trees 2 that was causing the issue. No idea why.

**Comment by hadeedsarfaraz** [comment]
JEI is trying to validate recipes before all trees  are loaded, so the recipe throws an error

**Comment by whatthedrunk** [comment]
Seems to still be happening so I made a post here if anyone wants to add anything.

https://github.com/mezz/JustEnoughItems/issues/1953

**Comment by whatthedrunk** [comment]
Looks like we had to remove Bonsai Trees. Thanks everyone especially @PeacefulBunny

**Comment by NikolaiSchreier** [comment]
Just a heads-up: I had a very similar sounding problem with an upgraded world, Bonsai Trees and JEI (in my case it was centered around the removal of Biomes O Plenty's ethereal_woods biome): https://github.com/thraaawn/BonsaiTrees/issues/200. I created a pull request but in the meantime built a forked version you can try as well: https://github.com/NikolaiSchreier/htmtmc/raw/main/minecraft/mods/BonsaiTrees-2.1.2.10-bopfix.jar
