### ISSUE TITLE
Redundant features/mods

### ISSUE THREAD

**Issue by redcatone** [AllTheMods/ATM-5#88]
Sign editing
* [Quark](https://quark.vazkii.net/#features) has a sign editing feature
![image](https://user-images.githubusercontent.com/24564581/79754597-60054c80-834a-11ea-8c1e-1c9d8c3203b0.png)
* [Edit Sign](https://www.curseforge.com/minecraft/mc-mods/edit-sign) mod seems redundant

Right click harvesting
* [Quark](https://quark.vazkii.net/#features) has a right click harvest ability
![image](https://user-images.githubusercontent.com/24564581/79754636-6eebff00-834a-11ea-9105-3b9ffbbc7495.png)
* [Reap Mod](https://www.curseforge.com/minecraft/mc-mods/reap-mod) seems redundant (ore excavation can replace the tree felling ability)

**Comment by whatthedrunk** [comment]
Thanks for the issue. I will test and remove in the next build.
