### ISSUE TITLE
FPS difference with Single Player vs Server

### ISSUE THREAD

**Issue by ovingiv** [AllTheMods/ATM-5#90]
## Expected Behavior

I'm getting 165+ fps when playing in single player on the same world.

## Current Behavior

I'm only getting ~30 fps while on the server.

## Possible Solution

I've tried changing power settings, overclocking, restarting the server.

https://imgur.com/a/qA5ChMi

**Comment by ovingiv** [comment]
At first I thought it was the way I was joining the server by using the "Searching for games on the network" so I joined by adding a server ip and I was getting my 150+ fps but after a while it went back to me only getting 30 fps.

**Comment by ovingiv** [comment]
So I figured out what is causing it. It's my HUGE JourneyMap save was causing it. I renamed the folder to what my server is and it brought back my fps.

**Comment by redcatone** [comment]
If you do `shift+f3` it will show you a pie graph oh your performance which you can narrow down with the number keys. I believe most of the issue is caused by journeymap waypoints which you can toggle off with `control+b`.

**Comment by ovingiv** [comment]
For those who are having the same issue with having too many waypoints,, disable seeing your waypoints in the JourneyMap settings by pushing J > options > Waypoint Beacons > uncheck Enable Waypoint Beacons.
