### ISSUE TITLE
Allthemodium Ore

### ISSUE THREAD

**Issue by VPower512** [AllTheMods/ATM-5#93]
## Current Behavior
I´ve the problem that I fount no allthemodium ore on my generated world. 
I used now the miner from mekanism and here i also can´t farm any ore. 
Could you please check this problem. 
Thanks in advance.

**Comment by Sarge2318** [comment]
Have you tried using the miner on new world gen?

**Comment by VPower512** [comment]
![2020-04-24_17 34 48](https://user-images.githubusercontent.com/64190542/80230335-1a9a9500-8652-11ea-8b8f-e908859b2ff1.png)
![2020-04-24_17 34 52](https://user-images.githubusercontent.com/64190542/80230338-1bcbc200-8652-11ea-809c-ccc56a372b42.png)
![2020-04-24_17 34 53](https://user-images.githubusercontent.com/64190542/80230342-1bcbc200-8652-11ea-8a13-8184e5058e6d.png)

**Comment by VPower512** [comment]
I mde a new world, here find the digital mine ore, but he shouldnt mine these ones.

**Comment by whatthedrunk** [comment]
Allthemodium cannot be mined from the Digital Miner or Quarry Plus.

**Comment by MrLuegner** [comment]
Hey is there any way that my Digital Miner can mine Allthemodium i did not find any Config for this mod?  My Miner find the Ores but cannot mine them.

**Comment by kkjdroid** [comment]
I'd also appreciate a config option for this.
