### ISSUE TITLE
Can't login in Server because of JourneyMap Server

### ISSUE THREAD

**Issue by Homeboy87** [AllTheMods/ATM-5#94]
If I try to join my Server running "All the Mods 5" V1.18b, I get a "Internal Error"
I deactivatet the Jorneymap  Server in the Mods and restartet the server and then it works.
But I want to use it. I will attach the log from the login.

## Possible Solution
disable Journey Map mod

## Log
[JourneyMAP SERVER.txt](https://github.com/AllTheMods/ATM-5/files/4530566/JourneyMAP.SERVER.txt)

**Comment by scotlandsyard** [comment]
I seem to have the same issue but it just keeps asking for dev mode on the server side and then timing out the client request.

**Comment by whatthedrunk** [comment]
Found this online. Let me know if it helps.

Try each step and connect before continuing on the next step:

Try resetting your computer

Try forcing an update to your client (don't forget to carry over your saves)

Try a fresh install of the server 

If you're running it locally (same computer) try putting the IP address as 'localhost', no single quotes. If that fails, you have a problem.

If it works but connecting via another IP (i.e. external IP, the one you give to your friends) fail, make sure your antivirus software is allowing the port through.

Check anyways if your antivirus / firewall is letting java through.

Restart your router/modem

**Comment by whatthedrunk** [comment]
Are you still having issues with version 1.22? If so we will reopen but I am not able to reproduce or find anyone with the issue.

**Comment by Homeboy87** [comment]
i rewrote my Ops.json and with the new one it works
