### ISSUE TITLE
Duping items with storage drawers and cyclic item cables

### ISSUE THREAD

**Issue by BaeleMarco** [AllTheMods/ATM-5#95]
## Expected Behavior
Pipe items out of Storage drawers with Cyclic pipes set to extract

## Current Behavior
Pipes out items into chest without actually taking out the items

## Possible Solution
/

## Steps to Reproduce
1. (optional?) Place auto miner from Mekanism 
2. Put storage drawers in a row with chest the end
3. Put Cyclic item cable on top
4. Use Cyclic wrench to set one pipe to extract
5. See chest being filled up with the item set to extract but doesn't extract from storage drawers

**Comment by whatthedrunk** [comment]
Thanks this has been reported to the mod dev. Going to close the issue for less visibility.
