### ISSUE TITLE
[Suggestion] Add overworld Rats mobs to soul shard spawner

### ISSUE THREAD

**Issue by jeremiahwinsley** [AllTheMods/ATM-5#97]
Pied Piper and Rat would be useful as soul shards. 

To add append to the entity list in `config/soulshards/soulshards.json`:
```
"rats:rat": true,
"rats:pied_piper": true
```

**Comment by whatthedrunk** [comment]
Until I test out Rats more on large servers I will leave this up to players to add. I will add this to my notes for the future though thanks!
