### ISSUE TITLE
Instant crash when trying to play from minecraft launcher

### ISSUE THREAD

**Issue by zanthra101** [AllTheMods/ATM-5#98]
Hi, 

Trying to launch the game from the minecraft launcher with 9gb ram allocated fails to launch. "An unexpected issue occurred". Installed mod pack via twitch, forge is 31.1.48, uninstalled and first install. Happened with ATM 4 but not 3 or remix. 

No reason it should not work, everything is up to date etc.

**Comment by Quu1337** [comment]
Your twitch is probably installed to folder with space, if the filepath has any folder with space, twitch just fails to work. Install it to somewhere else or use GDLauncher.

GDLauncher is preferred over twitch.
https://gdevs.io/
