### ISSUE TITLE
Super multi drill mod has no recipes

### ISSUE THREAD

**Issue by redcatone** [AllTheMods/ATM-5#99]
Basically all the parts for the mod are uncraftable as they have no recipes. This is intended as the mod author has [not decided](https://www.curseforge.com/minecraft/mc-mods/super-multi-drills?comment=89) on recipes yet. In the [changelog ](https://www.curseforge.com/minecraft/mc-mods/super-multi-drills/files/2936156) it is also mentioned that most recipes do not exist yet.
> - Some aspects of the mod may be incomplete right now. Most recipes are missing. All textures need to be redone.

Basically everything in the mod except for the final assembly and chassis need recipes through crafttweaker. Not even the drill blueprint has a recipe right now.

**Comment by whatthedrunk** [comment]
This was added for testing but figured the recipes would be in by now. If they don't add them soon I will add them or remove the mod until the dev is ready. Thanks!
